import { AppLanguage } from '../types/models';

/**
 * Exercise names are stored, matched and filtered as their English text — the
 * library ships from a public English database and the program catalogs name
 * their lifts the same way. So the English name stays the id and only the
 * label moves, exactly like equipment items and caution refinements.
 *
 * The map covers every exercise the program catalogs actually prescribe plus
 * the common library lifts a user meets while browsing. Anything else passes
 * through in English rather than guessing at a translation, which keeps a
 * missing entry honest instead of wrong.
 */
const EXERCISE_NAME_FI: Record<string, string> = {
  // ── Squat pattern ────────────────────────────────────────────────────
  'Back Squat': 'Takakyykky',
  'Barbell Squat': 'Takakyykky',
  'Barbell Full Squat': 'Takakyykky',
  'Front Squat': 'Etukyykky',
  'Hack Squat': 'Hack squat',
  'Box Squat': 'Laatikkokyykky',
  'Chair Squat': 'Tuolikyykky',
  'Bodyweight Squat': 'Kehonpainokyykky',
  'Goblet Squat': 'Goblet-kyykky',
  'Bulgarian Split Squat': 'Bulgarialainen askelkyykky',
  'Barbell Side Split Squat': 'Sivuaskelkyykky tangolla',
  'Sumo Squat': 'Sumokyykky',
  'Leg Press': 'Jalkaprässi',
  'Wall Sit': 'Seinäistunta',

  // ── Hinge pattern ────────────────────────────────────────────────────
  Deadlift: 'Maastaveto',
  'Barbell Deadlift': 'Maastaveto',
  'Romanian Deadlift': 'Romanialainen maastaveto',
  'Trap Bar Deadlift': 'Trap bar -maastaveto',
  'Sumo Deadlift': 'Sumomaastaveto',
  'Stiff-Legged Deadlift': 'Suorin jaloin maastaveto',
  'Good Morning': 'Aamunavaus',
  'Hip Thrust': 'Lantionnosto',
  'Barbell Hip Thrust': 'Lantionnosto tangolla',
  'Glute Bridge': 'Lantionnosto lattialla',
  'Kettlebell Swing': 'Kahvakuulaheilautus',
  'One-Arm Kettlebell Swings': 'Yhden käden kahvakuulaheilautus',
  'Cable Kickback': 'Taljapotku',

  // ── Lunges and single leg ────────────────────────────────────────────
  Lunge: 'Askelkyykky',
  'Walking Lunge': 'Kävelevä askelkyykky',
  'Bodyweight Walking Lunge': 'Kävelevä askelkyykky kehonpainolla',
  'Reverse Lunge': 'Taakse astuva askelkyykky',
  'Step-Up': 'Askelnousu',
  'Step-up with Knee Raise': 'Askelnousu polvennostolla',

  // ── Horizontal press ─────────────────────────────────────────────────
  'Bench Press': 'Penkkipunnerrus',
  'Barbell Bench Press - Medium Grip': 'Penkkipunnerrus',
  'Dumbbell Bench Press': 'Penkkipunnerrus käsipainoilla',
  'Incline Bench Press': 'Vinopenkkipunnerrus',
  'Barbell Incline Bench Press - Medium Grip': 'Vinopenkkipunnerrus',
  'Incline Dumbbell Press': 'Vinopenkkipunnerrus käsipainoilla',
  'Decline Bench Press': 'Laskeva penkkipunnerrus',
  'Close-Grip Bench Press': 'Kapea penkkipunnerrus',
  'Machine Chest Press': 'Rintaprässi',
  'Push-Up': 'Punnerrus',
  Pushups: 'Punnerrus',
  'Push-Up Wide': 'Leveä punnerrus',
  'Incline Push-Up': 'Vinopunnerrus',
  'Decline Push-Up': 'Laskeva punnerrus',
  Dips: 'Dipit',
  'Chest Dip': 'Rintadippi',

  // ── Vertical press ───────────────────────────────────────────────────
  'Overhead Press': 'Pystypunnerrus',
  'Standing Military Press': 'Pystypunnerrus',
  'Dumbbell Shoulder Press': 'Pystypunnerrus käsipainoilla',
  'Arnold Press': 'Arnold-punnerrus',
  'Push Press': 'Työntöpunnerrus',
  'Handstand Push-Ups': 'Käsilläseisontapunnerrus',

  // ── Chest isolation ──────────────────────────────────────────────────
  'Cable Fly': 'Taljaristikkäisveto',
  'Dumbbell Fly': 'Vipunosto rinnalle',
  // The pools spell it plural; the lookup is exact, so both spellings need an entry.
  'Dumbbell Flyes': 'Vipunosto rinnalle',
  'Pec Deck': 'Pec deck',

  // ── Vertical pull ────────────────────────────────────────────────────
  'Pull-Up': 'Leuanveto',
  Pullups: 'Leuanveto',
  'Chin-Up': 'Myötäotteinen leuanveto',
  Chinups: 'Myötäotteinen leuanveto',
  'Scapular Pull-Up': 'Lapaleuanveto',
  'Lat Pulldown': 'Ylätalja',
  'Wide-Grip Lat Pulldown': 'Leveä ylätalja',
  'Close-Grip Front Lat Pulldown': 'Kapea ylätalja',

  // ── Horizontal pull ──────────────────────────────────────────────────
  'Barbell Row': 'Tankosoutu',
  'Bent Over Barbell Row': 'Tankosoutu',
  'Dumbbell Row': 'Käsipainosoutu',
  'One-Arm Dumbbell Row': 'Yhden käden käsipainosoutu',
  'Seated Cable Row': 'Istuen taljasoutu',
  'Chest-Supported Row': 'Rintatuettu soutu',
  'T-Bar Row': 'T-tankosoutu',
  'Inverted Row': 'Kehonpainosoutu',
  'Face Pull': 'Kasvoilleveto',
  Shrug: 'Kohautus',
  'Barbell Shrug': 'Kohautus tangolla',

  // ── Shoulders ────────────────────────────────────────────────────────
  'Lateral Raise': 'Sivunosto',
  'Side Lateral Raise': 'Sivunosto',
  'Front Raise': 'Etunosto',
  'Rear Delt Fly': 'Takaolkapään vipunosto',
  'Reverse Machine Flyes': 'Takaolkapään laitevipunosto',
  'Band Pull Apart': 'Kuminauhan levitys',
  'Upright Row': 'Pystysoutu',

  // ── Biceps ───────────────────────────────────────────────────────────
  'Barbell Curl': 'Hauiskääntö tangolla',
  'Dumbbell Curl': 'Hauiskääntö käsipainoilla',
  'Dumbbell Bicep Curl': 'Hauiskääntö käsipainoilla',
  'Hammer Curl': 'Vasarakääntö',
  'Preacher Curl': 'Saarnaajakääntö',
  'Cable Curl': 'Taljakääntö',
  'Concentration Curls': 'Keskittymiskääntö',

  // ── Triceps ──────────────────────────────────────────────────────────
  'Triceps Pushdown': 'Ojentajapushdown',
  'Triceps Pushdown - Rope Attachment': 'Ojentajapushdown köydellä',
  'Overhead Triceps Extension': 'Ojentajapunnerrus pään yli',
  'Skull Crusher': 'Ranskalainen punnerrus',
  'Lying Triceps Press': 'Ranskalainen punnerrus',
  'Bench Dip': 'Penkkidippi',
  'Bench Dips': 'Penkkidippi',

  // ── Legs isolation ───────────────────────────────────────────────────
  'Leg Curl': 'Takareisikoukistus',
  'Seated Leg Curl': 'Istuen takareisikoukistus',
  'Lying Leg Curl': 'Maaten takareisikoukistus',
  'Leg Extension': 'Reiden ojennus',
  'Calf Raise': 'Pohjenosto',
  'Standing Calf Raise': 'Seisten pohjenosto',
  'Seated Calf Raise': 'Istuen pohjenosto',
  'Calf Press': 'Pohjeprässi',

  // ── Core ─────────────────────────────────────────────────────────────
  Plank: 'Lankku',
  'Side Plank': 'Kylkilankku',
  'Cable Crunch': 'Taljavatsarutistus',
  Crunches: 'Vatsarutistus',
  'Hanging Knee Raise': 'Roikkuen polvennosto',
  'Hanging Leg Raise': 'Roikkuen jalannosto',
  'Russian Twist': 'Venäläinen kierto',
  'Ab Wheel': 'Vatsarulla',
  'Mountain Climbers': 'Vuorikiipeilijä',
  'Mountain Climber': 'Vuorikiipeilijä',
  'Bicycle Crunch': 'Polkupyörärutistus',
  'Farmer Carry': 'Maanviljelijän kävely',

  // ── Conditioning and flows (catalog-only names) ──────────────────────
  Burpee: 'Burpee',
  'Treadmill HIIT (30s on / 30s off)': 'Juoksumatto-HIIT (30 s / 30 s)',
  'Bike HIIT (45s sprint / 15s rest)': 'Pyörä-HIIT (45 s veto / 15 s lepo)',
  'Easy Run Blocks': 'Kevyet juoksublokit',
  'Tempo Run Blocks': 'Tempojuoksublokit',
  'Stride Finishers': 'Askelkiihdytykset',
  'Rowing, Stationary': 'Soutulaite',
  'Bicycling, Stationary': 'Kuntopyörä',
  'Jump Rope': 'Hyppynaru',
  'Mobility Flow': 'Liikkuvuussarja',
  'Hip Mobility Flow': 'Lonkan liikkuvuussarja',
  'Recovery Stretch Flow': 'Palauttava venyttelysarja',
  'Sun Salutation Flow': 'Aurinkotervehdys',
  'Yoga Balance Flow': 'Joogan tasapainosarja',
  'Breath Reset': 'Hengityspalautus',
  'Dead Hang': 'Roikunta tangossa',

  // ═══ Reachable through the swap sheet and the plan composer ═════════
  // Everything above is what the ready programs prescribe. Everything
  // below is what a user can swap TO, or what the composer can add — the
  // substitution groups and the focus/supplemental pools. Those lists are
  // four times the size of the catalog, and until now they arrived in
  // English the moment anyone opened "Vaihda liike".

  // ── Squat and single leg ─────────────────────────────────────────────
  Squat: 'Kyykky',
  'Competition Back Squat': 'Kilpakyykky',
  'Pause Squat': 'Pysäytyskyykky',
  'Jump Squat': 'Hyppykyykky',
  'Squat Jump (20s on / 10s off)': 'Hyppykyykky (20 s / 10 s)',
  'Goblet Squat (Light)': 'Goblet-kyykky kevyellä',
  'Sit-to-Stand (Chair Squat)': 'Ylösnousu tuolilta',
  'Cossack Squat': 'Kasakkakyykky',
  'Deep Squat Hold': 'Syvä kyykkypito',
  'Supported Deep Squat Hold': 'Tuettu syvä kyykkypito',
  'Shrimp Squat': 'Shrimp-kyykky',
  'Sissy Squat': 'Sissy-kyykky',
  'Pistol Squat (each leg)': 'Pistoolikyykky (kumpikin jalka)',
  'Bulgarian Split Squat (Jumping)': 'Bulgarialainen askelkyykky hypyllä',
  'Step-Up (High Box)': 'Askelnousu korkealle',
  'Step-Up (Low Box)': 'Askelnousu matalalle',
  'Bodyweight Reverse Lunge': 'Taakse astuva askelkyykky kehonpainolla',
  'Curtsy Lunge': 'Ristiaskelkyykky',
  'Lateral Lunge': 'Sivuaskelkyykky',
  'Dumbbell Lunges': 'Askelkyykky käsipainoilla',

  // ── Hinge, glutes and hamstrings ─────────────────────────────────────
  'Conventional Deadlift': 'Perinteinen maastaveto',
  'Competition Deadlift': 'Kilpamaastaveto',
  'Deficit Deadlift': 'Maastaveto korokkeelta',
  'Single-Leg RDL': 'Yhden jalan romanialainen maastaveto',
  'Single-Leg Romanian Deadlift': 'Yhden jalan romanialainen maastaveto',
  'Romanian Deadlift (Light)': 'Romanialainen maastaveto kevyellä',
  'Glute Ham Raise': 'Takareisinosto',
  'Floor Glute-Ham Raise': 'Takareisinosto lattialla',
  'Nordic Hamstring Curl (Assisted)': 'Nordic-takareisikoukistus (avustettu)',
  'Hamstring Walkout': 'Takareisikävely',
  'Reverse Hyperextension': 'Käänteinen selänojennus',
  'Band Good Morning': 'Aamunavaus kuminauhalla',
  'Cable Pull-Through': 'Taljaveto jalkojen välistä',
  'Hip Thrust (Bodyweight)': 'Lantionnosto kehonpainolla',
  'Hip Thrust (Bodyweight or Light Bar)': 'Lantionnosto kehonpainolla tai kevyellä tangolla',
  'Single-Leg Hip Thrust': 'Yhden jalan lantionnosto',
  'Banded Hip Thrust': 'Lantionnosto kuminauhalla',
  'Glute Bridge (Banded)': 'Lantionnosto lattialla kuminauhalla',
  'Banded Glute Bridge': 'Lantionnosto lattialla kuminauhalla',
  'Single-Leg Glute Bridge': 'Yhden jalan lantionnosto lattialla',
  'Glute Bridge Hold': 'Lantionnostopito',
  'Glute Bridge March': 'Lantionnosto marssilla',
  'Butt Lift (Bridge)': 'Lantionnosto lattialla',
  'Frog Pump': 'Sammakkolantionnosto',
  'Frog Pump (Banded)': 'Sammakkolantionnosto kuminauhalla',
  'Glute Kickback': 'Pakarapotku',
  'Cable Glute Kickback': 'Pakarapotku taljassa',
  'One-Legged Cable Kickback': 'Yhden jalan taljapotku',
  'Banded Fire Hydrant': 'Palopostiliike kuminauhalla',
  'Standing Hip Abduction': 'Seisten lonkan loitonnus',
  'Cable Abductor': 'Lonkan loitonnus taljassa',
  'Side-Lying Leg Raise': 'Kylkimakuulla jalannosto',
  'Banded Lateral Walk': 'Sivuaskellus kuminauhalla',

  // ── Press ────────────────────────────────────────────────────────────
  'Barbell Bench Press': 'Penkkipunnerrus',
  'Competition Bench Press': 'Kilpapenkkipunnerrus',
  'Paused Bench Press': 'Pysäytyspenkkipunnerrus',
  'Incline Barbell Press': 'Vinopenkkipunnerrus tangolla',
  'Dumbbell Floor Press': 'Lattiapunnerrus käsipainoilla',
  'Machine Shoulder Press': 'Olkaprässi',
  'Seated Dumbbell Press': 'Istuen käsipainopunnerrus',
  'Standing Dumbbell Shoulder Press': 'Seisten käsipainopunnerrus',
  'Standing Overhead Press': 'Seisten pystypunnerrus',
  'Arnold Dumbbell Press': 'Arnold-punnerrus',
  'Dumbbell Thruster': 'Thruster käsipainoilla',
  'Push Up to Side Plank': 'Punnerrus kylkilankkuun',
  'Diamond Push-Up': 'Timanttipunnerrus',
  'Pike Push-Up': 'Pike-punnerrus',
  'Pike Push-Up (Elevated)': 'Pike-punnerrus korokkeelta',
  'Wall Push-Up': 'Seinäpunnerrus',
  'Push-Up (or Knee Push-Up)': 'Punnerrus (tai polvipunnerrus)',
  'Push-Up (20s on / 10s off)': 'Punnerrus (20 s / 10 s)',
  'Pseudo Planche Push-Up': 'Planche-punnerrus',
  'Plank-Up': 'Lankkunousu',
  'Body-Up': 'Lankkunousu',
  'Weighted Dips': 'Lisäpainodipit',
  'Triceps Dip (Chair)': 'Penkkidippi tuolilla',

  // ── Pull ─────────────────────────────────────────────────────────────
  'Weighted Pull-Up': 'Lisäpainoleuanveto',
  'Assisted Pull-Up': 'Avustettu leuanveto',
  'Explosive Pull-Up': 'Räjähtävä leuanveto',
  'Muscle-Up Progression (Negative)': 'Muscle up -harjoite (negatiivinen)',
  'Toes-to-Bar': 'Varpaat tankoon',
  'Rows (Bar or Rings)': 'Kehonpainosoutu (tanko tai renkaat)',
  'Inverted Row (Table)': 'Kehonpainosoutu pöydän alla',
  'Bodyweight Mid Row': 'Kehonpainosoutu',
  'Bent-Over Row': 'Tankosoutu',
  'Bent Over Two-Dumbbell Row': 'Käsipainosoutu kumarrettuna',
  'Single-Arm Dumbbell Row': 'Yhden käden käsipainosoutu',
  'Dumbbell Renegade Row': 'Renegade-soutu käsipainoilla',
  'Renegade Row': 'Renegade-soutu',
  'Pendlay Row': 'Pendlay-soutu',
  'Seated Machine Row': 'Istuen laitesoutu',
  'Machine High Row': 'Laitesoutu ylhäältä',
  'Cable Row': 'Taljasoutu',
  'Seated Cable Row (Wide)': 'Istuen leveä taljasoutu',
  'Standing Band Row': 'Seisten kuminauhasoutu',
  'Chest-Supported T-Bar Row': 'Rintatuettu T-tankosoutu',
  'Cable Pullover': 'Taljapullover',
  'Lat Pulldown (Wide Grip)': 'Leveä ylätalja',

  // ── Chest isolation ──────────────────────────────────────────────────
  'Cable Crossover': 'Taljaristikkäisveto',
  'Reverse Pec Deck': 'Käänteinen pec deck',
  'Doorway Pec Stretch': 'Rintalihasvenytys ovensuussa',
  'Inchworm to Push-Up': 'Toukkakävely punnerrukseen',

  // ── Shoulders ────────────────────────────────────────────────────────
  'Dumbbell Lateral Raise': 'Sivunosto käsipainoilla',
  'Cable Lateral Raise': 'Sivunosto taljassa',
  'Cable Front Raise': 'Etunosto taljassa',
  'Lateral Raise Superset': 'Sivunostosupersarja',
  'Dumbbell Rear Delt Fly': 'Takaolkapään vipunosto käsipainoilla',
  'Cable Rear Delt Fly': 'Takaolkapään vipunosto taljassa',
  'Band Pull-Apart': 'Kuminauhan levitys',
  'Arm Circles': 'Käsien pyöritykset',
  'Shoulder Dislocations (PVC)': 'Olkapään kierrot kepillä',
  'Wall Slide': 'Seinäliuku',
  'Thread the Needle': 'Neulansilmä',
  'Sphinx Pose': 'Sfinksiasento',

  // ── Arms ─────────────────────────────────────────────────────────────
  'Bicep Curl': 'Hauiskääntö',
  'EZ-Bar Curl': 'Hauiskääntö EZ-tangolla',
  'Cable Bicep Curl': 'Hauiskääntö taljassa',
  'Cable Hammer Curl': 'Vasarakääntö taljassa',
  'Alternate Hammer Curl': 'Vuorotteleva vasarakääntö',
  'Incline Dumbbell Curl': 'Vinopenkkihauiskääntö',
  'Cable Triceps Extension': 'Ojentajaojennus taljassa',
  'Cable Triceps Kickback': 'Ojentajapotku taljassa',
  'Triceps Kickback': 'Ojentajapotku',
  'Cable Triceps Pushdown': 'Ojentajapushdown taljassa',
  'Rope Pushdown': 'Ojentajapushdown köydellä',
  'Wrist Curl': 'Ranteen koukistus',
  'Reverse Wrist Curl': 'Ranteen ojennus',

  // ── Calves ───────────────────────────────────────────────────────────
  'Single-Leg Calf Raise': 'Yhden jalan pohjenosto',
  'Donkey Calf Raises': 'Aasipohjenosto',
  'Calf Raises - With Bands': 'Pohjenosto kuminauhalla',

  // ── Core ─────────────────────────────────────────────────────────────
  // Loan words keep their shape and take Finnish capitalisation, the way
  // "Hack squat" and "Pec deck" already do above.
  'Dead Bug': 'Dead bug',
  'Dead Bug (Modified)': 'Dead bug (helpotettu)',
  'Bird Dog': 'Bird dog',
  'Hollow Body Hold': 'Hollow-pito',
  'Dragon Flag': 'Dragon flag',
  'Front Lever Tuck Hold': 'Front lever -kippupito',
  'Tuck Planche Hold': 'Planche-kippupito',
  'L-Sit Hold': 'L-istunta',
  'V-Up': 'V-nosto',
  'Plank Jack': 'Lankkuhyppy',
  'Plank Shoulder Tap': 'Lankku olkakosketuksella',
  'Plank to Pike': 'Lankusta pikeen',
  'Side Plank (Knees Down)': 'Kylkilankku polvilta',
  'Transverse Abdominis Activation': 'Poikittaisen vatsalihaksen aktivointi',
  'Pelvic Floor Activation (Kegel)': 'Lantionpohjan aktivointi (Kegel)',
  'Vacuum (Stomach)': 'Vatsan vakuumi',
  'Standing Side Bend': 'Seisten kylkitaivutus',
  'Heel Slide': 'Kantapään liuku',
  'Standing Marching': 'Seisten marssi',
  'Medicine Ball Slam': 'Kuntopallon iskeminen',
  'Handstand Wall Walk': 'Käsilläseisonta seinää pitkin',
  'Wall Handstand Hold': 'Käsilläseisontapito seinää vasten',

  // ── Conditioning, jumps and sprints ──────────────────────────────────
  'High Knees': 'Polvennostojuoksu',
  'Jumping Jack': 'Haaraperushyppy',
  'Pogo Hops': 'Pogo-hypyt',
  'Box Jump': 'Laatikkohyppy',
  'Broad Jump': 'Pituushyppy paikaltaan',
  'Skater Jump': 'Luisteluhyppy',
  'Lateral Bound': 'Sivuloikka',
  'Sprint 40m': 'Sprintti 40 m',
  'Sprint Interval (200m)': 'Sprinttiveto (200 m)',
  'Cone Drill (Pro Agility)': 'Kartioharjoite (ketteryys)',
  'Ladder Drill': 'Tikasharjoite',
  'Heel-to-Toe Walk': 'Kantapää-varvas-kävely',
  'Battle Rope Slam': 'Battle rope -isku',
  'Battle Rope Wave': 'Battle rope -aalto',
  'Battling Ropes': 'Battle rope',
  'Sled Push': 'Kelkan työntö',
  "Farmer's Walk": 'Maanviljelijän kävely',
  'Power Clean': 'Rinnalleveto',
  'Air Bike (30s sprint)': 'Air bike (30 s veto)',
  'Stationary Bike (Easy Pace)': 'Kuntopyörä (kevyt vauhti)',
  'Recumbent Bike': 'Kuntopyörä selkänojalla',
  'Elliptical Trainer': 'Crosstrainer',
  'Jogging, Treadmill': 'Hölkkä juoksumatolla',
  'Trail Running/Walking': 'Polkujuoksu tai -kävely',
  'Rowing Machine (500m intervals)': 'Soutulaite (500 m vedot)',
  'Rowing Machine HIIT': 'Soutulaite-HIIT',
  'Stairmaster (Moderate)': 'Porraskone (kohtalainen)',
  'Burpee (20s on / 10s off)': 'Burpee (20 s / 10 s)',
  'Burpee with Push-Up': 'Burpee punnerruksella',
  'Mountain Climber (20s on / 10s off)': 'Vuorikiipeilijä (20 s / 10 s)',

  // ── Mobility, stretches and breathing ────────────────────────────────
  'Cat-Cow': 'Kissa-lehmä',
  'Cat Stretch': 'Kissavenytys',
  'Cobra Pose': 'Kobra-asento',
  'Cobra to Down Dog Flow': 'Kobrasta alaspäin katsovaan koiraan',
  "Child's Pose with Reach": 'Lapsen asento kurotuksella',
  'Pigeon Pose': 'Kyyhkynen',
  'Pigeon Pose (each side)': 'Kyyhkynen (kumpikin puoli)',
  'Butterfly Stretch': 'Perhosvenytys',
  'Frog Stretch': 'Sammakkovenytys',
  '90/90 Hip Stretch': '90/90-lonkkavenytys',
  'Seated Hip Stretch': 'Istuen lonkkavenytys',
  'Hip Flexor Stretch': 'Lonkankoukistajan venytys',
  'Couch Stretch (each side)': 'Lonkankoukistajan venytys (kumpikin puoli)',
  'Seated Pancake Stretch': 'Istuen haara-aukivenytys',
  'Seated Spinal Twist': 'Istuen selkärangan kierto',
  'Spinal Twist (Supine)': 'Selkärangan kierto selinmakuulla',
  'Sleeper Stretch': 'Sleeper-venytys',
  'Lying Quad Stretch': 'Etureiden venytys maaten',
  'All Fours Quad Stretch': 'Etureiden venytys konttausasennossa',
  'Standing Forward Fold': 'Seisten eteentaivutus',
  'Chin To Chest Stretch': 'Niskan venytys leuka rintaan',
  'Ankle Circles': 'Nilkan pyöritykset',
  'Ankle Mobility Drill': 'Nilkan liikkuvuusharjoite',
  'Hip Circles': 'Lonkan pyöritykset',
  'Thoracic Extension on Roller': 'Rintarangan ojennus rullalla',
  'Legs Up the Wall': 'Jalat seinää vasten',
  "World's Greatest Stretch": 'Maailman paras venytys',
  'Single-Leg Balance Hold': 'Yhden jalan tasapainopito',
  'Single-Leg Balance Reach': 'Yhden jalan tasapainokurotus',
  'Supported Single-Leg Balance': 'Tuettu yhden jalan tasapaino',
  'Box Breathing': 'Laatikkohengitys',
  'Diaphragmatic Breathing': 'Palleahengitys',
  'Breathing Reset': 'Hengityspalautus',
  'Cooldown Flow': 'Jäähdyttelysarja',
  'Recovery Stretch': 'Palauttava venytys',
  'Dynamic Warm-Up': 'Dynaaminen lämmittely',
  'Mobility Warm-Up': 'Liikkuvuuslämmittely',
  'Joint Prep Flow': 'Nivelten herättely',
};

/** The exercise name as the reader should see it; English is the stored id. */
export function exerciseNameLabel(language: AppLanguage, name: string): string {
  if (language !== 'fi') {
    return name;
  }
  return EXERCISE_NAME_FI[name.trim()] ?? name;
}

/** Exposed for the coverage test — every catalog lift should have an entry. */
export const TRANSLATED_EXERCISE_NAMES = EXERCISE_NAME_FI;
