const fs = require('node:fs');
const path = require('node:path');
const { AndroidConfig, withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');

/**
 * Nothing of the app's data leaves the phone through Android's own copying.
 *
 * `allowBackup="false"` (app.json) turns off cloud backup and `adb backup`.
 * Android 12 added a second channel it does not reliably cover: the
 * device-to-device transfer during a new phone's setup, which on many
 * devices takes every app's data unless the app's `dataExtractionRules`
 * say otherwise (PR review, 2026-09-15). These rules exclude every domain
 * from both channels, so the only copy of the training log that exists off
 * the phone is the app's own opt-in backup, the one the privacy policy
 * describes.
 *
 * The attribute is ignored below Android 12, where `allowBackup` alone is
 * the whole story. Lives here because `android/` is regenerated by prebuild.
 */
const RESOURCE_NAME = 'data_extraction_rules';

/** Every domain Android knows, excluded on both channels. */
const DOMAINS = ['root', 'file', 'database', 'sharedpref', 'external'];

function rulesXml() {
  const excludes = DOMAINS.map((domain) => `    <exclude domain="${domain}" />`).join('\n');
  return [
    '<?xml version="1.0" encoding="utf-8"?>',
    '<data-extraction-rules>',
    '  <cloud-backup>',
    excludes,
    '  </cloud-backup>',
    '  <device-transfer>',
    excludes,
    '  </device-transfer>',
    '</data-extraction-rules>',
    '',
  ].join('\n');
}

function applyDataExtractionRules(manifest) {
  const application = AndroidConfig.Manifest.getMainApplicationOrThrow(manifest);
  application.$['android:dataExtractionRules'] = `@xml/${RESOURCE_NAME}`;
  return manifest;
}

module.exports = function withDataExtractionRules(config) {
  config = withAndroidManifest(config, (config) => {
    applyDataExtractionRules(config.modResults);
    return config;
  });
  return withDangerousMod(config, [
    'android',
    (config) => {
      const target = path.join(config.modRequest.platformProjectRoot, 'app', 'src', 'main', 'res', 'xml', `${RESOURCE_NAME}.xml`);
      fs.mkdirSync(path.dirname(target), { recursive: true });
      fs.writeFileSync(target, rulesXml(), 'utf8');
      return config;
    },
  ]);
};

module.exports.applyDataExtractionRules = applyDataExtractionRules;
module.exports.rulesXml = rulesXml;
module.exports.DOMAINS = DOMAINS;
module.exports.RESOURCE_NAME = RESOURCE_NAME;
