const { withGradleProperties } = require('@expo/config-plugins');

/**
 * Which CPU architectures the app is built for.
 *
 * `android/` is gitignored and regenerated by `expo prebuild`, so a value set
 * there by hand survives exactly until the next prebuild. This is where it has
 * to live to be real.
 *
 * ── Why armeabi-v7a is not in the list ────────────────────────────────────
 *
 * It does not compile. NDK 27.1's clang 18.0.2 crashes with an internal
 * compiler error — the compiler's own bug, not our code — while compiling
 * react-native-svg's *generated* `Props.cpp` for 32-bit ARM at -O2. It dumps a
 * 6.5 MB reproducer and asks to be reported. The same file compiles for 64-bit
 * without complaint.
 *
 * Going back an NDK is closed: React Native 0.83's own `graphicsConversions.h`
 * calls `std::format`, which NDK 26's libc++ does not have, so 26.1 fails on
 * every architecture before it reaches any of ours. Measured, not assumed —
 * both were built.
 *
 * So the choice was between shipping without 32-bit ARM, lowering the
 * optimisation level for exactly the weakest devices to dodge a compiler bug,
 * or waiting on an NDK upgrade. Google requires 64-bit support and has not
 * required 32-bit since 2019; a 32-bit-only Android phone is a pre-2017 budget
 * device. Dropping it is a smaller loss than the alternatives, and the day the
 * ICE is fixed upstream this is one line to undo.
 *
 * x86_64 stays for a different reason and not for the store: it is what the
 * Android emulator runs on a PC, and dropping it would make every emulator
 * check on this project impossible. Play splits a bundle per device, so
 * carrying it costs a user nothing.
 */
const ARCHITECTURES = ['arm64-v8a', 'x86_64'];

/** Exported so a test can assert the retired one has not crept back. */
const RETIRED_ARCHITECTURES = ['armeabi-v7a', 'x86'];

function applyBuildArchitectures(properties) {
  const value = ARCHITECTURES.join(',');
  const existing = properties.find(
    (item) => item.type === 'property' && item.key === 'reactNativeArchitectures',
  );

  if (existing) {
    existing.value = value;
    return properties;
  }

  properties.push({ type: 'property', key: 'reactNativeArchitectures', value });
  return properties;
}

module.exports = function withBuildArchitectures(config) {
  return withGradleProperties(config, (config) => {
    applyBuildArchitectures(config.modResults);
    return config;
  });
};

module.exports.applyBuildArchitectures = applyBuildArchitectures;
module.exports.ARCHITECTURES = ARCHITECTURES;
module.exports.RETIRED_ARCHITECTURES = RETIRED_ARCHITECTURES;
