const { withGradleProperties } = require('@expo/config-plugins');

/**
 * How big the AsyncStorage database may grow on Android.
 *
 * The library caps its SQLite file at 6 MB unless told otherwise
 * (`AsyncStorage_db_size_in_MB`, read in its `android/config.gradle`), and a
 * write past the cap fails with "database or disk is full". Every logged
 * session adds about 8 KB and nothing is ever trimmed, so 6 MB is roughly 650
 * sessions — a few years of steady training, or one Hevy import from somebody
 * who has used Hevy for a few years. Past it, every save fails from then on.
 *
 * 64 MB is not a target; it moves the wall far enough that the next limit is
 * how long a full save takes, which is the SQLite move in the architecture
 * plan, and not a cap that refuses the write outright.
 *
 * Same reason as withBuildArchitectures for living here: `android/` is
 * regenerated by `expo prebuild`, so a value set there by hand does not last.
 */
const DATABASE_SIZE_MB = 64;
const KEY = 'AsyncStorage_db_size_in_MB';

function applyStorageSize(properties) {
  const value = String(DATABASE_SIZE_MB);
  const existing = properties.find((item) => item.type === 'property' && item.key === KEY);

  if (existing) {
    existing.value = value;
    return properties;
  }

  properties.push({ type: 'property', key: KEY, value });
  return properties;
}

module.exports = function withStorageSize(config) {
  return withGradleProperties(config, (config) => {
    applyStorageSize(config.modResults);
    return config;
  });
};

module.exports.applyStorageSize = applyStorageSize;
module.exports.DATABASE_SIZE_MB = DATABASE_SIZE_MB;
module.exports.STORAGE_SIZE_KEY = KEY;
