const assert = require('node:assert/strict');

/**
 * Android's own backup of the app's data is off, and the setting is real.
 *
 * `android:allowBackup` defaults to true and Expo's template leaves it unset,
 * so the whole AsyncStorage — every session, the account email, the coach's
 * memory — went into the device's Google backup and `adb backup`. The
 * manifest is regenerated by `expo prebuild`, so the attribute has to come
 * from a config plugin; a value set by hand reverts on the next prebuild.
 */
const { applyAllowBackup } = require('../../plugins/withAllowBackup.js');
const appConfig = require('../../app.json');

function manifest(applicationAttributes) {
  return {
    manifest: {
      $: { 'xmlns:android': 'http://schemas.android.com/apk/res/android' },
      application: [{ $: applicationAttributes, activity: [] }],
    },
  };
}

module.exports = [
  {
    name: 'allowBackup: the plugin is registered, or it never runs',
    run() {
      const plugins = appConfig.expo.plugins.map((entry) => (Array.isArray(entry) ? entry[0] : entry));
      assert.ok(plugins.includes('./plugins/withAllowBackup.js'), 'the allowBackup plugin is not in app.json');
    },
  },
  {
    name: 'allowBackup: the attribute is false whether prebuild wrote one or not',
    run() {
      // Expo's template: no attribute at all, which Android reads as true.
      const fresh = applyAllowBackup(manifest({ 'android:name': '.MainApplication' }));
      assert.equal(fresh.manifest.application[0].$['android:allowBackup'], 'false');
      // Everything else prebuild wrote is left alone.
      assert.equal(fresh.manifest.application[0].$['android:name'], '.MainApplication');

      // A template that turned it on explicitly is overridden, not added to.
      const explicit = applyAllowBackup(manifest({ 'android:name': '.MainApplication', 'android:allowBackup': 'true' }));
      assert.equal(explicit.manifest.application[0].$['android:allowBackup'], 'false');
      assert.equal(Object.keys(explicit.manifest.application[0].$).length, 2);
    },
  },
  {
    name: 'allowBackup: a manifest with no application element is an error, not a silent skip',
    run() {
      assert.throws(() => applyAllowBackup({ manifest: { $: {} } }));
    },
  },
];
