const assert = require('node:assert/strict');

/**
 * Which architectures the app is built for, and that the setting is real.
 *
 * `android/gradle.properties` is generated by `expo prebuild`, so the value has
 * to be written by a config plugin — one set by hand there survives until the
 * next prebuild and then quietly reverts to all four. That reversion is the
 * failure this file is aimed at: it would not break a build on a phone, it
 * would break the release build, and only on the machine that runs it.
 */
const {
  applyBuildArchitectures,
  ARCHITECTURES,
  RETIRED_ARCHITECTURES,
} = require('../../plugins/withBuildArchitectures.js');
const appConfig = require('../../app.json');

const KEY = 'reactNativeArchitectures';

function valueOf(properties) {
  return properties.find((item) => item.type === 'property' && item.key === KEY)?.value ?? null;
}

module.exports = [
  {
    name: 'architectures: the plugin is registered, or it never runs',
    run() {
      const plugins = appConfig.expo.plugins.map((entry) => (Array.isArray(entry) ? entry[0] : entry));
      assert.ok(
        plugins.includes('./plugins/withBuildArchitectures.js'),
        'the architecture plugin is not in app.json, so prebuild will not apply it',
      );
    },
  },
  {
    name: 'architectures: 32-bit ARM stays out, because it does not compile',
    run() {
      // NDK 27.1's clang crashes on react-native-svg's generated Props.cpp for
      // armv7, and NDK 26 is too old for React Native 0.83. Until that changes
      // upstream, a build that includes it fails.
      for (const retired of RETIRED_ARCHITECTURES) {
        assert.ok(!ARCHITECTURES.includes(retired), `${retired} is back in the build`);
      }
      // 64-bit ARM is the whole point: it is what a phone runs.
      assert.ok(ARCHITECTURES.includes('arm64-v8a'));
      // And x86_64 is what the emulator runs on a PC.
      assert.ok(ARCHITECTURES.includes('x86_64'));
    },
  },
  {
    name: 'architectures: prebuild gets the value whether the property exists or not',
    run() {
      // Fresh tree: the property is not there yet.
      const fresh = applyBuildArchitectures([]);
      assert.equal(valueOf(fresh), ARCHITECTURES.join(','));

      // The ordinary case: prebuild writes its own default first, and this has
      // to overwrite it rather than add a second line the parser ignores.
      const generated = [
        { type: 'comment', value: 'Use this property to specify which architecture you want to build.' },
        { type: 'property', key: KEY, value: 'armeabi-v7a,arm64-v8a,x86,x86_64' },
        { type: 'property', key: 'newArchEnabled', value: 'true' },
      ];
      const applied = applyBuildArchitectures(generated);
      assert.equal(valueOf(applied), ARCHITECTURES.join(','));
      assert.equal(applied.filter((item) => item.key === KEY).length, 1, 'the property is set twice');
      // Everything else prebuild wrote is left alone.
      assert.equal(valueOf(applied.filter((item) => item.key === KEY)), ARCHITECTURES.join(','));
      assert.ok(applied.some((item) => item.key === 'newArchEnabled'));
      assert.ok(applied.some((item) => item.type === 'comment'));
    },
  },
];
