const assert = require('node:assert/strict');

/**
 * Android 12's device-to-device transfer is told to take nothing.
 *
 * `allowBackup="false"` covers cloud backup and `adb backup`, but not
 * reliably the cable transfer during a new phone's setup, which defaults to
 * every app's data unless `dataExtractionRules` exclude it (PR review,
 * 2026-09-15). The rules are written by a plugin because `android/` is
 * regenerated by prebuild.
 */
const {
  DOMAINS,
  RESOURCE_NAME,
  applyDataExtractionRules,
  rulesXml,
} = require('../../plugins/withDataExtractionRules.js');
const appConfig = require('../../app.json');

module.exports = [
  {
    name: 'dataExtractionRules: the plugin is registered, or it never runs',
    run() {
      const plugins = appConfig.expo.plugins.map((entry) => (Array.isArray(entry) ? entry[0] : entry));
      assert.ok(plugins.includes('./plugins/withDataExtractionRules.js'));
    },
  },
  {
    name: 'dataExtractionRules: the manifest points at the rules and every domain is excluded on both channels',
    run() {
      const manifest = {
        manifest: {
          $: { 'xmlns:android': 'http://schemas.android.com/apk/res/android' },
          application: [{ $: { 'android:name': '.MainApplication', 'android:allowBackup': 'false' }, activity: [] }],
        },
      };
      const written = applyDataExtractionRules(manifest);
      assert.equal(written.manifest.application[0].$['android:dataExtractionRules'], `@xml/${RESOURCE_NAME}`);
      assert.equal(written.manifest.application[0].$['android:allowBackup'], 'false', 'the other attribute is gone');

      const xml = rulesXml();
      assert.deepEqual(DOMAINS, ['root', 'file', 'database', 'sharedpref', 'external']);
      for (const channel of ['cloud-backup', 'device-transfer']) {
        const section = xml.slice(xml.indexOf(`<${channel}>`), xml.indexOf(`</${channel}>`));
        assert.ok(section.length > 0, `${channel} is missing`);
        for (const domain of DOMAINS) {
          assert.ok(section.includes(`<exclude domain="${domain}" />`), `${domain} is not excluded from ${channel}`);
        }
        assert.doesNotMatch(section, /<include/, `${channel} includes something`);
      }
      assert.throws(() => applyDataExtractionRules({ manifest: { $: {} } }));
    },
  },
];
