const assert = require('node:assert/strict');

/**
 * The AsyncStorage size cap on Android, and that the setting is real.
 *
 * The library stops writes at 6 MB unless a gradle property says otherwise, and
 * `android/gradle.properties` is regenerated by `expo prebuild`, so the value
 * has to come from a config plugin. A cap that reverts would not fail any
 * build; it would fail every save for somebody with a few years of history.
 */
const { applyStorageSize, DATABASE_SIZE_MB, STORAGE_SIZE_KEY } = require('../../plugins/withStorageSize.js');
const appConfig = require('../../app.json');

function valueOf(properties) {
  return properties.find((item) => item.type === 'property' && item.key === STORAGE_SIZE_KEY)?.value ?? null;
}

module.exports = [
  {
    name: 'storage size: the plugin is registered, or it never runs',
    run() {
      const plugins = appConfig.expo.plugins.map((entry) => (Array.isArray(entry) ? entry[0] : entry));
      assert.ok(plugins.includes('./plugins/withStorageSize.js'), 'the storage size plugin is not in app.json');
    },
  },
  {
    name: 'storage size: the property is the one the library reads, above its 6 MB default',
    run() {
      // Spelled exactly as async-storage's android/config.gradle reads it; a
      // near miss is ignored without a warning.
      assert.equal(STORAGE_SIZE_KEY, 'AsyncStorage_db_size_in_MB');
      assert.ok(Number.isInteger(DATABASE_SIZE_MB) && DATABASE_SIZE_MB > 6);

      const fresh = applyStorageSize([]);
      assert.equal(valueOf(fresh), String(DATABASE_SIZE_MB));

      const generated = [
        { type: 'property', key: STORAGE_SIZE_KEY, value: '6' },
        { type: 'property', key: 'newArchEnabled', value: 'true' },
      ];
      const applied = applyStorageSize(generated);
      assert.equal(valueOf(applied), String(DATABASE_SIZE_MB));
      assert.equal(applied.filter((item) => item.key === STORAGE_SIZE_KEY).length, 1, 'the property is set twice');
      assert.ok(applied.some((item) => item.key === 'newArchEnabled'));
    },
  },
];
