/**
 * The guard in front of every store build.
 *
 *   node scripts/releaseGuard.cjs --platform ios       before a store build
 *   node scripts/releaseGuard.cjs --platform ios --mark   after the store accepted it
 *
 * iOS build numbers raise themselves (EAS autoIncrement); the version the
 * store shows (`expo.version` in app.json) does not, and a build carrying the
 * version already in the store is one nobody meant to make. So a store
 * release leaves a tag, `<platform>-v<version>`, and the guard refuses a build
 * whose version has that tag already or is not above the last one. A second
 * TestFlight build of a version not yet released passes: the tag is set only
 * with --mark, once that version is live.
 *
 * Android is built locally with Gradle — EAS autoIncrement never runs for it,
 * and Gradle does not read app.json: android/ is generated by `expo prebuild`,
 * which writes versionCode and versionName into android/app/build.gradle. So
 * the guard refuses a build while that file disagrees with app.json (or does
 * not exist), and while the code is not above the last released one — the Android
 * tag is annotated with the code it shipped (`versionCode=N`). Google Play
 * rejects a repeated code, and the build only finds that out after it is done.
 * When the newest Android tag records no code (made by hand, or before this),
 * the operator records it once: `node scripts/releaseGuard.cjs --platform android
 * --record-code N`, which annotates that tag (and pushes it) so the guard
 * remembers. `--released-code N` states it for one run only; npm forwards extra
 * arguments to the last command of a script, so neither goes through
 * `npm run release:android` — call the script with node.
 *
 * It also prints what went in since the last release, the start of the
 * "what's new" text, and writes it to release-notes/<platform>-<version>.md
 * for editing — the stores want it, and one person cannot remember it.
 */
const { execFileSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');
const readline = require('node:readline');

const ROOT = path.join(__dirname, '..');
const PLATFORMS = ['ios', 'android'];

function parseVersion(text) {
  const match = /^(\d+)\.(\d+)\.(\d+)$/.exec(String(text ?? '').trim());
  return match ? match.slice(1).map(Number) : null;
}

function compareVersions(a, b) {
  const left = parseVersion(a);
  const right = parseVersion(b);
  for (let i = 0; i < 3; i += 1) {
    if (left[i] !== right[i]) {
      return left[i] < right[i] ? -1 : 1;
    }
  }
  return 0;
}

function tagFor(platform, version) {
  return `${platform}-v${version}`;
}

/** The released versions of a platform, from its tags, newest first. */
function releasedVersions(platform, tags) {
  const prefix = `${platform}-v`;
  return tags
    .filter((tag) => tag.startsWith(prefix) && parseVersion(tag.slice(prefix.length)))
    .map((tag) => tag.slice(prefix.length))
    .sort((a, b) => compareVersions(b, a));
}

/** The versionCode a tag message records, or null when it records none. */
function parseVersionCode(message) {
  const match = /(?:^|\s)versionCode=(\d+)(?:\s|$)/.exec(String(message ?? ''));
  return match ? Number(match[1]) : null;
}

/** The annotation `--mark` puts on a tag: the Android build number it shipped. */
function tagMessageFor({ platform, versionCode }) {
  return platform === 'android' ? `versionCode=${versionCode}` : null;
}

function isBuildCode(value) {
  return Number.isInteger(value) && value > 0;
}

/**
 * The versionCode and versionName `expo prebuild` wrote into build.gradle;
 * null for whichever is not there.
 */
function parseGradleVersion(text) {
  const source = String(text ?? '');
  const code = /^[ \t]*versionCode[ \t]+(\d+)[ \t]*\r?$/m.exec(source);
  const name = /^[ \t]*versionName[ \t]+"([^"\r\n]*)"/m.exec(source);
  return { versionCode: code ? Number(code[1]) : null, versionName: name ? name[1] : null };
}

// The repo's shell is PowerShell, where `CI=1 cmd` is not a command; bash is the other half.
const PREBUILD = 'npx expo prebuild --clean (PowerShell: $env:CI=1; npx expo prebuild --clean, bash: CI=1 npx expo prebuild --clean)';

/** What the guard prints about the build number — true for the platform. */
function buildLine({ platform, version, versionCode }) {
  if (platform === 'android') {
    return (
      `Kauppabuildi: android ${version}, versionCode ${versionCode} ` +
      `(Gradle ei nosta sitä: nosta se app.jsonissa käsin ja aja ${PREBUILD} ennen buildia).`
    );
  }
  return `Kauppabuildi: ${platform} ${version} (buildinumero nousee automaattisesti, EAS).`;
}

/**
 * Whether a store build of `version` may go ahead.
 * `{ ok: true, previous }` or `{ ok: false, reason }`; previous is the last
 * released version, null before the first release.
 *
 * For Android also
 *   versionCode   what app.json says
 *   taggedCodes   { <version>: code | null } for the android tags
 *   declaredCode  --released-code: the code the newest tag's build shipped
 *   gradle        { versionCode, versionName } from android/app/build.gradle,
 *                 null when there is no android/ folder yet
 */
function decide({ platform, version, tags, versionCode, taggedCodes = {}, declaredCode, gradle }) {
  if (!PLATFORMS.includes(platform)) {
    return { ok: false, reason: `Tuntematon alusta "${platform}". Käytä --platform ios tai --platform android.` };
  }
  if (!parseVersion(version)) {
    return { ok: false, reason: `app.jsonin expo.version "${version}" ei ole muotoa X.Y.Z.` };
  }
  const released = releasedVersions(platform, tags);
  const previous = released[0] ?? null;
  if (released.includes(version)) {
    return {
      ok: false,
      previous,
      reason:
        `Versio ${version} on jo julkaistu (${platform}). Nosta expo.version app.jsonissa ` +
        `(esim. ${suggestNext(version)}) ennen uutta kauppabuildia.`,
    };
  }
  if (previous && compareVersions(version, previous) < 0) {
    return {
      ok: false,
      previous,
      reason: `Versio ${version} on pienempi kuin viimeksi julkaistu ${previous} (${platform}). Kaupat eivät ota sitä vastaan.`,
    };
  }
  if (platform === 'android') {
    if (!isBuildCode(versionCode)) {
      return {
        ok: false,
        previous,
        reason: `app.jsonin expo.android.versionCode "${versionCode}" ei ole positiivinen kokonaisluku.`,
      };
    }
    if (previous) {
      // The newest release is the one the next build follows. Its number comes
      // from its own tag or from the operator; an older tag's number is no
      // substitute, it can be far below what actually shipped.
      const newest = taggedCodes[previous];
      const declared = isBuildCode(declaredCode) ? declaredCode : null;
      if (!isBuildCode(newest) && declared === null) {
        return {
          ok: false,
          previous,
          reason:
            `Tagi ${tagFor(platform, previous)} ei kerro mikä versionCode sen buildissa oli, joten seuraavan rajaa ei tiedetä. ` +
            'Aja kerran: node scripts/releaseGuard.cjs --platform android --record-code N ' +
            `(N = julkaistun buildin versionCode, Play Consolesta; komento merkitsee koodin tagiin ${tagFor(platform, previous)} ja työntää sen, ` +
            'joten se muistetaan). Älä käytä npm run release:android -- ...: npm antaa argumentit vain ketjun viimeiselle komennolle. ' +
            'Jatkossa julkaisu merkitään komennolla release:android:done.',
        };
      }
      const recorded = Object.values(taggedCodes).filter(isBuildCode);
      const floor = Math.max(...recorded, declared ?? 0);
      if (versionCode <= floor) {
        return {
          ok: false,
          previous,
          reason:
            `app.jsonin expo.android.versionCode on ${versionCode}, mutta jo julkaistu koodi on ${floor}. ` +
            `Google Play ei ota vastaan jo käytettyä koodia. Nosta versionCode arvoon ${floor + 1} tai ylemmäs ` +
            `app.jsonissa ja aja ${PREBUILD} ennen buildia (Gradle ei nosta sitä itse).`,
        };
      }
    }
    if (!gradle) {
      return {
        ok: false,
        previous,
        reason:
          'android/-kansiota ei ole. Gradle ei lue app.jsonia: versionCode ja versionName tulevat prebuildin tekemästä ' +
          `android/app/build.gradle-tiedostosta. Aja ${PREBUILD} ennen buildia.`,
      };
    }
    if (gradle.versionCode !== versionCode || gradle.versionName !== version) {
      return {
        ok: false,
        previous,
        reason:
          `android/app/build.gradle on versionCode ${gradle.versionCode ?? '(puuttuu)'}, versionName ${gradle.versionName ?? '(puuttuu)'}, ` +
          `mutta app.json sanoo ${versionCode} ja ${version}. Gradle ei lue app.jsonia, joten APK saisi vanhat luvut. ` +
          `Aja ${PREBUILD} ennen buildia.`,
      };
    }
  }
  return { ok: true, previous };
}

function suggestNext(version) {
  const [major, minor] = parseVersion(version);
  return `${major}.${minor + 1}.0`;
}

/** The "what's new" draft from commit subjects since the last release. */
function releaseNotes({ platform, version, previous, subjects }) {
  const lines = [`# ${platform === 'ios' ? 'iOS' : 'Android'} ${version}`, ''];
  lines.push(previous ? `Muutokset version ${previous} jälkeen:` : 'Ensimmäinen julkaisu.');
  if (previous) {
    lines.push('');
    if (subjects.length === 0) {
      lines.push('- (ei committeja edellisen julkaisun jälkeen)');
    }
    for (const subject of subjects) {
      lines.push(`- ${subject}`);
    }
  }
  return `${lines.join('\n')}\n`;
}

function git(args) {
  // stderr is piped, not dropped: a failed command carries it on the error, so a
  // push that git refused can say why.
  return execFileSync('git', args, { cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim();
}

/**
 * Why a push failed, in the operator's terms: git's own text, and whether the
 * remote could not be reached (try again later) or answered no (a person has
 * to look — the tag exists there, or the remote moved).
 */
function describePushFailure(tag, error) {
  const text = String(error?.stderr ?? '').trim() || String(error?.message ?? error).trim();
  const rejected = /rejected|non-fast-forward|already exists|stale info|failed to push some refs|denied|permission/i;
  const unreachable =
    /could not resolve host|unable to access|could not read from remote|does not appear to be a git repository|connection (?:refused|timed out|reset)|timed out|network is unreachable|unable to connect|repository not found|no route to host/i;
  // "failed to push some refs" follows a rejection and a network failure alike,
  // so an unreachable signal wins over the generic line.
  const kind = unreachable.test(text) ? 'unreachable' : rejected.test(text) ? 'rejected' : 'unknown';
  const head = {
    unreachable: `Tagin ${tag} työntö originiin epäonnistui: origin ei vastaa.`,
    rejected: `Tagin ${tag} työntö originiin epäonnistui: origin hylkäsi sen.`,
    unknown: `Tagin ${tag} työntö originiin epäonnistui.`,
  }[kind];
  const advice =
    kind === 'rejected'
      ? 'Tarkista mitä originissa on tälle tagille (git ls-remote --tags origin); älä pakota työntöä ennen sitä.'
      : `Tagi ${tag} on vain tällä koneella. Aja sama komento uudelleen kun origin vastaa.`;
  return `${head}\n${text.split('\n').map((line) => `  git: ${line}`).join('\n')}\n${advice}`;
}

function readApp() {
  const expo = JSON.parse(fs.readFileSync(path.join(ROOT, 'app.json'), 'utf8'))?.expo;
  return { version: expo?.version, versionCode: expo?.android?.versionCode };
}

/**
 * The versionCode each android tag records, `{ <version>: code | null }`, read
 * from the whole annotation (a message may have several paragraphs). Records
 * are NUL-separated because a message can hold any other character; a
 * lightweight tag has no annotation and records nothing.
 */
function readTaggedCodes() {
  const rows = git(['for-each-ref', 'refs/tags/android-v*', '--format=%(refname:short)%09%(objecttype)%09%(contents)%00']);
  const codes = {};
  for (const row of rows.split('\0')) {
    const [name, type, ...rest] = row.trim().split('\t');
    const version = name?.startsWith('android-v') ? name.slice('android-v'.length) : null;
    if (version && parseVersion(version)) {
      codes[version] = type === 'tag' ? parseVersionCode(rest.join('\t')) : null;
    }
  }
  return codes;
}

/** android/app/build.gradle as prebuild left it; null when there is none. */
function readGradle() {
  try {
    return parseGradleVersion(fs.readFileSync(path.join(ROOT, 'android', 'app', 'build.gradle'), 'utf8'));
  } catch {
    return null;
  }
}

/**
 * Tag a released version and make sure origin has the tag. `run` is `git` that
 * throws on failure, so a failed push cannot read as a finished mark. Returns
 * `{ code, lines }`: what to print, and the exit code.
 *
 * A tag that exists here but not on origin is the leftover of a push that
 * failed; marking again pushes it, and a remote that cannot be asked fails the
 * run rather than assuming the tag went up.
 */
function markRelease({ platform, version, versionCode, run }) {
  if (!PLATFORMS.includes(platform)) {
    return { code: 1, lines: ['Käytä --platform ios tai --platform android.'] };
  }
  if (platform === 'android' && !isBuildCode(versionCode)) {
    return { code: 1, lines: [`app.jsonin expo.android.versionCode "${versionCode}" ei ole positiivinen kokonaisluku.`] };
  }
  const tag = tagFor(platform, version);
  const retry = `Tagi ${tag} on vain tällä koneella. Aja sama komento uudelleen kun origin vastaa.`;
  const pushIt = () => {
    try {
      run(['push', 'origin', tag]);
      return null;
    } catch (error) {
      return describePushFailure(tag, error);
    }
  };

  if (run(['tag', '--list', tag]) === tag) {
    const full = run(['rev-parse', `${tag}^{commit}`]);
    const sha = full.slice(0, 7);
    let remoteRows;
    try {
      remoteRows = run(['ls-remote', '--tags', 'origin', `refs/tags/${tag}`, `refs/tags/${tag}^{}`]);
    } catch {
      return {
        code: 1,
        lines: [`Tagi ${tag} (${sha}) on olemassa, mutta originiin ei saada yhteyttä: ei tiedetä onko se työnnetty. ${retry}`],
      };
    }
    if (remoteRows !== '') {
      // An annotated tag lists its commit on the peeled `^{}` row.
      const rows = remoteRows.split('\n').map((row) => row.split('\t'));
      const remoteCommit = (rows.find(([, ref]) => ref?.endsWith('^{}')) ?? rows[0])[0];
      if (remoteCommit !== full) {
        return {
          code: 1,
          lines: [
            `Tagi ${tag} osoittaa täällä commitiin ${sha} mutta originissa commitiin ${remoteCommit.slice(0, 7)}: ` +
              'ne kertovat eri julkaisusta. Selvitä kumpi on se mikä kauppaan meni; älä merkitse uudelleen ennen sitä.',
          ],
        };
      }
      return { code: 0, lines: [`${tag} on jo merkitty (${sha}).`] };
    }
    const failure = pushIt();
    if (failure) {
      return { code: 1, lines: [failure] };
    }
    return { code: 0, lines: [`Tagi ${tag} (${sha}) oli vain tällä koneella; työnnetty originiin. Seuraava kauppabuildi vaatii uuden version.`] };
  }

  const lines = [];
  const sha = run(['rev-parse', '--short', 'HEAD']);
  if (run(['status', '--porcelain', '--untracked-files=no']) !== '') {
    lines.push('Varoitus: työpuussa on tallentamattomia muutoksia; tagi osoittaa silti HEADiin eikä sisällä niitä.');
  }
  const message = tagMessageFor({ platform, versionCode });
  run(message ? ['tag', '-a', tag, '-m', message] : ['tag', tag]);
  lines.push(`Tagi ${tag} asetettu commitiin ${sha} (HEAD).`);
  const failure = pushIt();
  if (failure) {
    return { code: 1, lines: [...lines, failure] };
  }
  lines.push(`Merkitty julkaistuksi: ${tag}. Seuraava kauppabuildi vaatii uuden version.`);
  return { code: 0, lines };
}

/**
 * Records the versionCode a release shipped on its (existing) tag: the tag is
 * re-made as an annotated `versionCode=N` tag on the SAME commit and pushed
 * over the old one. This is the remedy for a newest tag that records no code;
 * unlike `--released-code` it is remembered, in the tag. A tag that records a
 * different code, or that points at another commit on origin, is refused: that
 * is two stories about one release.
 */
function recordCode({ platform, tag, code, run }) {
  if (platform !== 'android') {
    return { code: 1, lines: ['--record-code kuuluu Androidille: käytä --platform android.'] };
  }
  if (!isBuildCode(code)) {
    return { code: 1, lines: [`--record-code vaatii positiivisen kokonaisluvun (versionCode), sai "${code}".`] };
  }
  let name = tag;
  if (!name) {
    const newest = releasedVersions('android', run(['tag', '--list']).split('\n').filter(Boolean))[0];
    if (!newest) {
      return { code: 1, lines: ['Android-tageja ei ole: ei ole mihin merkitä. Anna tagi: --tag android-vX.Y.Z.'] };
    }
    name = tagFor('android', newest);
  }
  if (run(['tag', '--list', name]) !== name) {
    return { code: 1, lines: [`Tagia ${name} ei ole tällä koneella. Hae tagit (git fetch --tags) tai anna oikea --tag.`] };
  }
  const recorded =
    run(['cat-file', '-t', name]) === 'tag' ? parseVersionCode(run(['tag', '--list', '--format=%(contents)', name])) : null;
  if (recorded !== null && recorded !== code) {
    return {
      code: 1,
      lines: [`Tagi ${name} kertoo jo versionCoden ${recorded}, ei ${code}. Selvitä kumpi meni kauppaan; tagia ei muuteta.`],
    };
  }
  const full = run(['rev-parse', `${name}^{commit}`]);
  const lines = [];
  if (recorded === null) {
    run(['tag', '--force', '-a', name, '-m', `versionCode=${code}`, full]);
    lines.push(`Tagi ${name} (${full.slice(0, 7)}) merkitty: versionCode=${code}.`);
  }
  const object = run(['rev-parse', name]);
  let rows;
  try {
    rows = run(['ls-remote', '--tags', 'origin', `refs/tags/${name}`, `refs/tags/${name}^{}`]);
  } catch (error) {
    return {
      code: 1,
      lines: [...lines, `Originiin ei saada yhteyttä, joten tagin ${name} tilaa siellä ei tiedetä. Aja sama komento uudelleen kun origin vastaa.`, `  git: ${String(error?.stderr ?? error?.message ?? error).trim()}`],
    };
  }
  const remote = rows === '' ? [] : rows.split('\n').map((row) => row.split('\t'));
  const remoteObject = remote.find(([, ref]) => ref === `refs/tags/${name}`)?.[0] ?? null;
  const remoteCommit = remote.find(([, ref]) => ref?.endsWith('^{}'))?.[0] ?? remoteObject;
  if (remoteCommit && remoteCommit !== full) {
    return {
      code: 1,
      lines: [
        ...lines,
        `Tagi ${name} osoittaa täällä commitiin ${full.slice(0, 7)} mutta originissa commitiin ${remoteCommit.slice(0, 7)}: ` +
          'ne kertovat eri julkaisusta. Selvitä kumpi on se mikä kauppaan meni; origin jätettiin ennalleen.',
      ],
    };
  }
  if (remoteObject === object) {
    return { code: 0, lines: [...lines, `Tagi ${name} kertoo versionCoden ${code} myös originissa.`] };
  }
  try {
    // Only this tag, and only because it is the same commit being annotated.
    run(['push', '--force', 'origin', `refs/tags/${name}`]);
  } catch (error) {
    return { code: 1, lines: [...lines, describePushFailure(name, error)] };
  }
  return { code: 0, lines: [...lines, `Tagi ${name} työnnetty originiin. Guard muistaa nyt koodin ${code}.`] };
}

/** `--name value` or `--name=value`; undefined when absent, '' when given without a value. */
function argValue(args, name) {
  const index = args.findIndex((arg) => arg === name || arg.startsWith(`${name}=`));
  if (index < 0) {
    return undefined;
  }
  if (args[index].startsWith(`${name}=`)) {
    return args[index].slice(name.length + 1);
  }
  const next = args[index + 1];
  return next === undefined || next.startsWith('--') ? '' : next;
}

/** A positive integer from a flag's text, null when the text is not one. */
function codeFromFlag(text) {
  return /^\d+$/.test(String(text ?? '').trim()) && Number(text) > 0 ? Number(text) : null;
}

async function confirm(question) {
  if (!process.stdin.isTTY || process.env.CI) {
    return true;
  }
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  const answer = await new Promise((resolve) => rl.question(question, resolve));
  rl.close();
  return /^(k|kyllä|y|yes)$/i.test(answer.trim());
}

async function main(args) {
  const platform = argValue(args, '--platform');
  const { version, versionCode } = readApp();
  try {
    // The tags another machine set: best effort, offline still checks local ones.
    git(['fetch', '--tags', '--quiet']);
  } catch {
    console.warn('Tagien haku epäonnistui, tarkistetaan vain paikalliset tagit.');
  }
  const tags = git(['tag', '--list']).split('\n').filter(Boolean);

  const recordFlag = argValue(args, '--record-code');
  if (recordFlag !== undefined) {
    const result = recordCode({
      platform,
      tag: argValue(args, '--tag') || undefined,
      code: codeFromFlag(recordFlag),
      run: git,
    });
    for (const line of result.lines) {
      (result.code === 0 ? console.log : console.error)(line);
    }
    return result.code;
  }

  const releasedFlag = argValue(args, '--released-code');
  if (releasedFlag !== undefined && codeFromFlag(releasedFlag) === null) {
    console.error(`--released-code vaatii positiivisen kokonaisluvun (julkaistun buildin versionCode), sai "${releasedFlag}".`);
    return 1;
  }

  if (args.includes('--mark')) {
    const result = markRelease({ platform, version, versionCode, run: git });
    for (const line of result.lines) {
      (result.code === 0 ? console.log : console.error)(line);
    }
    return result.code;
  }

  const android = platform === 'android';
  const decision = decide({
    platform,
    version,
    tags,
    versionCode,
    taggedCodes: android ? readTaggedCodes() : {},
    declaredCode: codeFromFlag(releasedFlag) ?? undefined,
    gradle: android ? readGradle() : undefined,
  });
  if (!decision.ok) {
    console.error(`\n✋ ${decision.reason}\n`);
    return 1;
  }
  let subjects = [];
  if (decision.previous) {
    subjects = git(['log', '--no-merges', '--pretty=%s', `${tagFor(platform, decision.previous)}..HEAD`])
      .split('\n')
      .filter(Boolean);
  }
  const notes = releaseNotes({ platform, version, previous: decision.previous, subjects });
  const notesFile = path.join(ROOT, 'release-notes', `${platform}-${version}.md`);
  if (!fs.existsSync(notesFile)) {
    fs.mkdirSync(path.dirname(notesFile), { recursive: true });
    fs.writeFileSync(notesFile, notes);
  }
  console.log(`\n${buildLine({ platform, version, versionCode })}`);
  console.log(`Viimeksi julkaistu: ${decision.previous ?? 'ei vielä mitään'}.\n`);
  console.log(notes);
  console.log(`Muutosluonnos: ${path.relative(ROOT, notesFile)}\n`);
  if (!(await confirm(`Onko ${version} oikea versio tälle julkaisulle? (k/e) `))) {
    console.error('Peruttu. Nosta expo.version app.jsonissa ja aja uudelleen.');
    return 1;
  }
  return 0;
}

if (require.main === module) {
  main(process.argv.slice(2)).then(
    (code) => process.exit(code),
    (error) => {
      console.error(error);
      process.exit(1);
    },
  );
}

module.exports = {
  buildLine,
  compareVersions,
  decide,
  markRelease,
  recordCode,
  describePushFailure,
  parseGradleVersion,
  parseVersionCode,
  releaseNotes,
  releasedVersions,
  tagFor,
  tagMessageFor,
};
