import { WorkoutSubstitutionGroup, WorkoutTemplateExercise, WorkoutTemplateSession, WorkoutTemplateV1 } from './workoutTypes';

function ex(exercise: WorkoutTemplateExercise) {
  return exercise;
}

function session(sessionDef: WorkoutTemplateSession) {
  return sessionDef;
}

export const WORKOUT_SUBSTITUTION_GROUPS: WorkoutSubstitutionGroup[] = [
  { id: 'squat_pattern', allowedExerciseNames: ['Back Squat', 'Front Squat', 'Hack Squat', 'Leg Press'] },
  { id: 'hinge_pattern', allowedExerciseNames: ['Romanian Deadlift', 'Trap Bar Deadlift', 'Hip Thrust'] },
  { id: 'horizontal_press', allowedExerciseNames: ['Bench Press', 'Dumbbell Bench Press', 'Machine Chest Press', 'Incline Bench Press', 'Incline Dumbbell Press'] },
  { id: 'vertical_press', allowedExerciseNames: ['Overhead Press', 'Dumbbell Shoulder Press', 'Machine Shoulder Press'] },
  { id: 'horizontal_pull', allowedExerciseNames: ['Chest-Supported Row', 'Seated Cable Row', 'Barbell Row'] },
  { id: 'vertical_pull', allowedExerciseNames: ['Lat Pulldown', 'Assisted Pull-Up', 'Pull-Up'] },
  { id: 'single_leg', allowedExerciseNames: ['Reverse Lunge', 'Walking Lunge', 'Bulgarian Split Squat'] },
  { id: 'accessory_arms', allowedExerciseNames: ['Triceps Pushdown', 'Dumbbell Curl', 'Hammer Curl'] },
  { id: 'accessory_delts', allowedExerciseNames: ['Lateral Raise', 'Rear Delt Fly'] },
  { id: 'accessory_core', allowedExerciseNames: ['Cable Crunch', 'Hanging Knee Raise'] },
  { id: 'calves', allowedExerciseNames: ['Calf Raise'] },
  { id: 'accessory_hamstrings', allowedExerciseNames: ['Leg Curl'] },
  { id: 'mobility_flow', allowedExerciseNames: ['Mobility Flow', 'Hip Mobility Flow', 'Recovery Stretch Flow'] },
  { id: 'yoga_flow', allowedExerciseNames: ['Sun Salutation Flow', 'Yoga Balance Flow', 'Breath Reset'] },
  { id: 'running_blocks', allowedExerciseNames: ['Easy Run Blocks', 'Tempo Run Blocks', 'Stride Finishers'] },
];

export const WORKOUT_TEMPLATES_V1: WorkoutTemplateV1[] = [
  {
    id: 'tpl_3_day_full_body_v1',
    name: '3-Day Full Body',
    goalType: 'general',
    level: 'beginner',
    splitType: 'full_body',
    daysPerWeek: 3,
    estimatedSessionDuration: 50,
    progressionModel: 'double_progression',
    defaultScheduleMode: 'rolling_sequence',
    progressionRules: {
      primary: 'Use double progression on anchor lifts. When the last hard set reaches repsMax with clean form, increase load next time by the smallest practical increment.',
      secondary: 'Use the same rule, but keep load stable longer if fatigue rises. Prefer completing the rep range before adding weight.',
      accessory: 'Add reps before load. When repsMax is repeatable, use a small load increase; otherwise repeat the same load.',
      failureHandling: 'If repsMin is missed, repeat the same load once. If the same target is missed twice in a row, reduce load by 5-10% and rebuild.',
    },
    sessions: [
      session({ id: 'full_body_a', name: 'Full Body A', orderIndex: 1, exercises: [
        ex({ id: 'full_body_a_back_squat', exerciseName: 'Back Squat', slotId: 'primary_squat_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 6, repsMax: 8, restSecondsMin: 120, restSecondsMax: 180, substitutionGroup: 'squat_pattern' }),
        ex({ id: 'full_body_a_bench_press', exerciseName: 'Bench Press', slotId: 'primary_press_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 6, repsMax: 8, restSecondsMin: 120, restSecondsMax: 180, substitutionGroup: 'horizontal_press' }),
        ex({ id: 'full_body_a_chest_supported_row', exerciseName: 'Chest-Supported Row', slotId: 'primary_pull_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 8, repsMax: 10, restSecondsMin: 120, restSecondsMax: 180, substitutionGroup: 'horizontal_pull' }),
        ex({ id: 'full_body_a_romanian_deadlift', exerciseName: 'Romanian Deadlift', slotId: 'secondary_hinge_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 2, repsMin: 8, repsMax: 10, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'hinge_pattern' }),
        ex({ id: 'full_body_a_cable_crunch', exerciseName: 'Cable Crunch', slotId: 'accessory_core_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_core' }),
      ] }),
      session({ id: 'full_body_b', name: 'Full Body B', orderIndex: 2, exercises: [
        ex({ id: 'full_body_b_leg_press', exerciseName: 'Leg Press', slotId: 'primary_squat_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 8, repsMax: 10, restSecondsMin: 120, restSecondsMax: 180, substitutionGroup: 'squat_pattern' }),
        ex({ id: 'full_body_b_overhead_press', exerciseName: 'Overhead Press', slotId: 'primary_press_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 6, repsMax: 8, restSecondsMin: 120, restSecondsMax: 180, substitutionGroup: 'vertical_press' }),
        ex({ id: 'full_body_b_lat_pulldown', exerciseName: 'Lat Pulldown', slotId: 'primary_pull_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 8, repsMax: 10, restSecondsMin: 120, restSecondsMax: 180, substitutionGroup: 'vertical_pull' }),
        ex({ id: 'full_body_b_reverse_lunge', exerciseName: 'Reverse Lunge', slotId: 'secondary_single_leg_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 2, repsMin: 8, repsMax: 10, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'single_leg' }),
        ex({ id: 'full_body_b_triceps_pushdown', exerciseName: 'Triceps Pushdown', slotId: 'accessory_arms_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_arms' }),
      ] }),
      session({ id: 'full_body_c', name: 'Full Body C', orderIndex: 3, exercises: [
        ex({ id: 'full_body_c_hip_thrust', exerciseName: 'Hip Thrust', slotId: 'primary_hinge_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 8, repsMax: 10, restSecondsMin: 120, restSecondsMax: 180, substitutionGroup: 'hinge_pattern' }),
        ex({ id: 'full_body_c_incline_dumbbell_press', exerciseName: 'Incline Dumbbell Press', slotId: 'primary_press_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 8, repsMax: 10, restSecondsMin: 120, restSecondsMax: 180, substitutionGroup: 'horizontal_press' }),
        ex({ id: 'full_body_c_seated_cable_row', exerciseName: 'Seated Cable Row', slotId: 'primary_pull_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 8, repsMax: 10, restSecondsMin: 120, restSecondsMax: 180, substitutionGroup: 'horizontal_pull' }),
        ex({ id: 'full_body_c_leg_curl', exerciseName: 'Leg Curl', slotId: 'secondary_hamstrings_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'accessory_hamstrings' }),
        ex({ id: 'full_body_c_cable_crunch', exerciseName: 'Cable Crunch', slotId: 'accessory_core_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_core' }),
      ] }),
    ],
  },
  {
    id: 'tpl_4_day_upper_lower_v1',
    name: '4-Day Upper/Lower',
    goalType: 'hypertrophy',
    level: 'intermediate',
    splitType: 'upper_lower',
    daysPerWeek: 4,
    estimatedSessionDuration: 55,
    progressionModel: 'double_progression',
    defaultScheduleMode: 'rolling_sequence',
    progressionRules: {
      primary: 'Use double progression on anchor lifts. When the last hard set reaches repsMax with clean form, increase load next time by the smallest practical increment.',
      secondary: 'Use the same rule, but keep load stable longer if fatigue rises. Prefer completing the rep range before adding weight.',
      accessory: 'Add reps before load. When repsMax is repeatable, use a small load increase; otherwise repeat the same load.',
      failureHandling: 'If repsMin is missed, repeat the same load once. If the same target is missed twice in a row, reduce load by 5-10% and rebuild.',
    },
    sessions: [
      session({ id: 'upper_a', name: 'Upper A', orderIndex: 1, exercises: [
        ex({ id: 'upper_a_bench_press', exerciseName: 'Bench Press', slotId: 'primary_press_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 5, repsMax: 8, restSecondsMin: 120, restSecondsMax: 180, substitutionGroup: 'horizontal_press' }),
        ex({ id: 'upper_a_chest_supported_row', exerciseName: 'Chest-Supported Row', slotId: 'primary_pull_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 6, repsMax: 8, restSecondsMin: 120, restSecondsMax: 180, substitutionGroup: 'horizontal_pull' }),
        ex({ id: 'upper_a_incline_dumbbell_press', exerciseName: 'Incline Dumbbell Press', slotId: 'secondary_press_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 2, repsMin: 8, repsMax: 10, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'horizontal_press' }),
        ex({ id: 'upper_a_lat_pulldown', exerciseName: 'Lat Pulldown', slotId: 'secondary_pull_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 2, repsMin: 8, repsMax: 10, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'vertical_pull' }),
        ex({ id: 'upper_a_lateral_raise', exerciseName: 'Lateral Raise', slotId: 'accessory_delts_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 12, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_delts' }),
        ex({ id: 'upper_a_triceps_pushdown', exerciseName: 'Triceps Pushdown', slotId: 'accessory_arms_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_arms' }),
      ] }),
      session({ id: 'lower_a', name: 'Lower A', orderIndex: 2, exercises: [
        ex({ id: 'lower_a_back_squat', exerciseName: 'Back Squat', slotId: 'primary_squat_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 5, repsMax: 8, restSecondsMin: 120, restSecondsMax: 180, substitutionGroup: 'squat_pattern' }),
        ex({ id: 'lower_a_romanian_deadlift', exerciseName: 'Romanian Deadlift', slotId: 'primary_hinge_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 6, repsMax: 8, restSecondsMin: 120, restSecondsMax: 180, substitutionGroup: 'hinge_pattern' }),
        ex({ id: 'lower_a_leg_press', exerciseName: 'Leg Press', slotId: 'secondary_squat_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 2, repsMin: 8, repsMax: 10, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'squat_pattern' }),
        ex({ id: 'lower_a_leg_curl', exerciseName: 'Leg Curl', slotId: 'accessory_hamstrings_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_hamstrings' }),
        ex({ id: 'lower_a_calf_raise', exerciseName: 'Calf Raise', slotId: 'calves_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 12, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'calves' }),
        ex({ id: 'lower_a_cable_crunch', exerciseName: 'Cable Crunch', slotId: 'accessory_core_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_core' }),
      ] }),
      session({ id: 'upper_b', name: 'Upper B', orderIndex: 3, exercises: [
        ex({ id: 'upper_b_overhead_press', exerciseName: 'Overhead Press', slotId: 'primary_press_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 5, repsMax: 8, restSecondsMin: 120, restSecondsMax: 180, substitutionGroup: 'vertical_press' }),
        ex({ id: 'upper_b_seated_cable_row', exerciseName: 'Seated Cable Row', slotId: 'primary_pull_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 6, repsMax: 8, restSecondsMin: 120, restSecondsMax: 180, substitutionGroup: 'horizontal_pull' }),
        ex({ id: 'upper_b_machine_chest_press', exerciseName: 'Machine Chest Press', slotId: 'secondary_press_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 2, repsMin: 8, repsMax: 10, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'horizontal_press' }),
        ex({ id: 'upper_b_lat_pulldown', exerciseName: 'Lat Pulldown', slotId: 'secondary_pull_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 2, repsMin: 8, repsMax: 10, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'vertical_pull' }),
        ex({ id: 'upper_b_rear_delt_fly', exerciseName: 'Rear Delt Fly', slotId: 'accessory_delts_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 12, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_delts' }),
        ex({ id: 'upper_b_dumbbell_curl', exerciseName: 'Dumbbell Curl', slotId: 'accessory_arms_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_arms' }),
      ] }),
      session({ id: 'lower_b', name: 'Lower B', orderIndex: 4, exercises: [
        ex({ id: 'lower_b_trap_bar_deadlift', exerciseName: 'Trap Bar Deadlift', slotId: 'primary_hinge_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 4, repsMax: 6, restSecondsMin: 120, restSecondsMax: 180, substitutionGroup: 'hinge_pattern' }),
        ex({ id: 'lower_b_leg_press', exerciseName: 'Leg Press', slotId: 'secondary_squat_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 3, repsMin: 8, repsMax: 10, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'squat_pattern' }),
        ex({ id: 'lower_b_bulgarian_split_squat', exerciseName: 'Bulgarian Split Squat', slotId: 'secondary_single_leg_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 2, repsMin: 8, repsMax: 10, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'single_leg' }),
        ex({ id: 'lower_b_leg_curl', exerciseName: 'Leg Curl', slotId: 'accessory_hamstrings_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_hamstrings' }),
        ex({ id: 'lower_b_calf_raise', exerciseName: 'Calf Raise', slotId: 'calves_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 12, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'calves' }),
        ex({ id: 'lower_b_hanging_knee_raise', exerciseName: 'Hanging Knee Raise', slotId: 'accessory_core_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'bodyweight', sets: 2, repsMin: 10, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_core' }),
      ] }),
    ],
  },
  {
    id: 'tpl_5_day_hybrid_v1',
    name: '5-Day Hybrid',
    goalType: 'hypertrophy',
    level: 'intermediate',
    splitType: 'hybrid',
    daysPerWeek: 5,
    estimatedSessionDuration: 55,
    progressionModel: 'double_progression',
    defaultScheduleMode: 'rolling_sequence',
    progressionRules: {
      primary: 'Use double progression on anchor lifts. When the last hard set reaches repsMax with clean form, increase load next time by the smallest practical increment.',
      secondary: 'Use the same rule, but keep load stable longer if fatigue rises. Prefer completing the rep range before adding weight.',
      accessory: 'Add reps before load. When repsMax is repeatable, use a small load increase; otherwise repeat the same load.',
      failureHandling: 'If repsMin is missed, repeat the same load once. If the same target is missed twice in a row, reduce load by 5-10% and rebuild.',
    },
    sessions: [
      session({ id: 'upper_a', name: 'Upper A', orderIndex: 1, exercises: [
        ex({ id: 'upper_a_bench_press', exerciseName: 'Bench Press', slotId: 'primary_press_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 5, repsMax: 8, restSecondsMin: 120, restSecondsMax: 180, substitutionGroup: 'horizontal_press' }),
        ex({ id: 'upper_a_chest_supported_row', exerciseName: 'Chest-Supported Row', slotId: 'primary_pull_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 6, repsMax: 8, restSecondsMin: 120, restSecondsMax: 180, substitutionGroup: 'horizontal_pull' }),
        ex({ id: 'upper_a_incline_dumbbell_press', exerciseName: 'Incline Dumbbell Press', slotId: 'secondary_press_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 2, repsMin: 8, repsMax: 10, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'horizontal_press' }),
        ex({ id: 'upper_a_lat_pulldown', exerciseName: 'Lat Pulldown', slotId: 'secondary_pull_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 2, repsMin: 8, repsMax: 10, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'vertical_pull' }),
        ex({ id: 'upper_a_lateral_raise', exerciseName: 'Lateral Raise', slotId: 'accessory_delts_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 12, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_delts' }),
      ] }),
      session({ id: 'lower_a', name: 'Lower A', orderIndex: 2, exercises: [
        ex({ id: 'lower_a_back_squat', exerciseName: 'Back Squat', slotId: 'primary_squat_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 5, repsMax: 8, restSecondsMin: 120, restSecondsMax: 180, substitutionGroup: 'squat_pattern' }),
        ex({ id: 'lower_a_romanian_deadlift', exerciseName: 'Romanian Deadlift', slotId: 'primary_hinge_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 6, repsMax: 8, restSecondsMin: 120, restSecondsMax: 180, substitutionGroup: 'hinge_pattern' }),
        ex({ id: 'lower_a_leg_press', exerciseName: 'Leg Press', slotId: 'secondary_squat_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 2, repsMin: 8, repsMax: 10, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'squat_pattern' }),
        ex({ id: 'lower_a_leg_curl', exerciseName: 'Leg Curl', slotId: 'accessory_hamstrings_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_hamstrings' }),
        ex({ id: 'lower_a_calf_raise', exerciseName: 'Calf Raise', slotId: 'calves_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 12, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'calves' }),
      ] }),
      session({ id: 'push', name: 'Push', orderIndex: 3, exercises: [
        ex({ id: 'push_incline_bench_press', exerciseName: 'Incline Bench Press', slotId: 'primary_press_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 6, repsMax: 8, restSecondsMin: 120, restSecondsMax: 180, substitutionGroup: 'horizontal_press' }),
        ex({ id: 'push_overhead_press', exerciseName: 'Overhead Press', slotId: 'primary_press_2', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 6, repsMax: 8, restSecondsMin: 120, restSecondsMax: 180, substitutionGroup: 'vertical_press' }),
        ex({ id: 'push_machine_chest_press', exerciseName: 'Machine Chest Press', slotId: 'secondary_press_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 2, repsMin: 8, repsMax: 10, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'horizontal_press' }),
        ex({ id: 'push_lateral_raise', exerciseName: 'Lateral Raise', slotId: 'accessory_delts_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 3, repsMin: 12, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_delts' }),
        ex({ id: 'push_triceps_pushdown', exerciseName: 'Triceps Pushdown', slotId: 'accessory_arms_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_arms' }),
      ] }),
      session({ id: 'pull', name: 'Pull', orderIndex: 4, exercises: [
        ex({ id: 'pull_lat_pulldown', exerciseName: 'Lat Pulldown', slotId: 'primary_pull_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 6, repsMax: 10, restSecondsMin: 120, restSecondsMax: 180, substitutionGroup: 'vertical_pull' }),
        ex({ id: 'pull_chest_supported_row', exerciseName: 'Chest-Supported Row', slotId: 'primary_pull_2', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 6, repsMax: 8, restSecondsMin: 120, restSecondsMax: 180, substitutionGroup: 'horizontal_pull' }),
        ex({ id: 'pull_rear_delt_fly', exerciseName: 'Rear Delt Fly', slotId: 'accessory_delts_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 12, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_delts' }),
        ex({ id: 'pull_dumbbell_curl', exerciseName: 'Dumbbell Curl', slotId: 'accessory_arms_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_arms' }),
        ex({ id: 'pull_hammer_curl', exerciseName: 'Hammer Curl', slotId: 'accessory_arms_2', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_arms' }),
      ] }),
      session({ id: 'lower_b', name: 'Lower B', orderIndex: 5, exercises: [
        ex({ id: 'lower_b_trap_bar_deadlift', exerciseName: 'Trap Bar Deadlift', slotId: 'primary_hinge_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 4, repsMax: 6, restSecondsMin: 120, restSecondsMax: 180, substitutionGroup: 'hinge_pattern' }),
        ex({ id: 'lower_b_leg_press', exerciseName: 'Leg Press', slotId: 'secondary_squat_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 3, repsMin: 8, repsMax: 10, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'squat_pattern' }),
        ex({ id: 'lower_b_bulgarian_split_squat', exerciseName: 'Bulgarian Split Squat', slotId: 'secondary_single_leg_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 2, repsMin: 8, repsMax: 10, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'single_leg' }),
        ex({ id: 'lower_b_leg_curl', exerciseName: 'Leg Curl', slotId: 'accessory_hamstrings_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_hamstrings' }),
        ex({ id: 'lower_b_calf_raise', exerciseName: 'Calf Raise', slotId: 'calves_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 12, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'calves' }),
        ex({ id: 'lower_b_cable_crunch', exerciseName: 'Cable Crunch', slotId: 'accessory_core_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_core' }),
      ] }),
    ],
  },
  {
    id: 'tpl_2_day_minimal_full_body_v1',
    name: '2-Day Minimal Full Body',
    goalType: 'general',
    level: 'beginner',
    splitType: 'full_body',
    daysPerWeek: 2,
    estimatedSessionDuration: 45,
    progressionModel: 'double_progression',
    defaultScheduleMode: 'rolling_sequence',
    progressionRules: {
      primary: 'Use double progression on anchor lifts. When the last hard set reaches repsMax with clean form, increase load next time by the smallest practical increment.',
      secondary: 'Use the same rule, but keep load stable longer if fatigue rises. Prefer completing the rep range before adding weight.',
      accessory: 'Add reps before load. When repsMax is repeatable, use a small load increase; otherwise repeat the same load.',
      failureHandling: 'If repsMin is missed, repeat the same load once. If the same target is missed twice in a row, reduce load by 5-10% and rebuild.',
    },
    sessions: [
      session({ id: 'minimal_full_body_a', name: 'Minimal A', orderIndex: 1, exercises: [
        ex({ id: 'minimal_full_body_a_back_squat', exerciseName: 'Back Squat', slotId: 'primary_squat_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 5, repsMax: 8, restSecondsMin: 120, restSecondsMax: 180, substitutionGroup: 'squat_pattern' }),
        ex({ id: 'minimal_full_body_a_bench_press', exerciseName: 'Bench Press', slotId: 'primary_press_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 5, repsMax: 8, restSecondsMin: 120, restSecondsMax: 180, substitutionGroup: 'horizontal_press' }),
        ex({ id: 'minimal_full_body_a_chest_supported_row', exerciseName: 'Chest-Supported Row', slotId: 'primary_pull_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 6, repsMax: 8, restSecondsMin: 120, restSecondsMax: 180, substitutionGroup: 'horizontal_pull' }),
        ex({ id: 'minimal_full_body_a_cable_crunch', exerciseName: 'Cable Crunch', slotId: 'accessory_core_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_core' }),
      ] }),
      session({ id: 'minimal_full_body_b', name: 'Minimal B', orderIndex: 2, exercises: [
        ex({ id: 'minimal_full_body_b_leg_press', exerciseName: 'Leg Press', slotId: 'primary_squat_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 8, repsMax: 10, restSecondsMin: 120, restSecondsMax: 180, substitutionGroup: 'squat_pattern' }),
        ex({ id: 'minimal_full_body_b_overhead_press', exerciseName: 'Overhead Press', slotId: 'primary_press_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 5, repsMax: 8, restSecondsMin: 120, restSecondsMax: 180, substitutionGroup: 'vertical_press' }),
        ex({ id: 'minimal_full_body_b_lat_pulldown', exerciseName: 'Lat Pulldown', slotId: 'primary_pull_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 8, repsMax: 10, restSecondsMin: 120, restSecondsMax: 180, substitutionGroup: 'vertical_pull' }),
        ex({ id: 'minimal_full_body_b_leg_curl', exerciseName: 'Leg Curl', slotId: 'accessory_hamstrings_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_hamstrings' }),
      ] }),
    ],
  },
  {
    id: 'tpl_3_day_strength_base_v1',
    name: '3-Day Strength Base',
    goalType: 'strength',
    level: 'beginner',
    splitType: 'full_body',
    daysPerWeek: 3,
    estimatedSessionDuration: 55,
    progressionModel: 'double_progression',
    defaultScheduleMode: 'rolling_sequence',
    progressionRules: {
      primary: 'Drive the main lift with lower-rep double progression. Add load only when all planned sets stay crisp and inside the rep range.',
      secondary: 'Keep secondary lifts one step lighter than the main lift and progress more slowly than the anchors.',
      accessory: 'Use accessories to keep weak links moving, but do not let them limit recovery for the next heavy day.',
      failureHandling: 'If the first work set misses repsMin, repeat the load next time. If it stalls twice, reduce load by 5% and rebuild with clean reps.',
    },
    sessions: [
      session({ id: 'strength_base_a', name: 'Strength A', orderIndex: 1, exercises: [
        ex({ id: 'strength_base_a_back_squat', exerciseName: 'Back Squat', slotId: 'primary_squat_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 4, repsMin: 4, repsMax: 6, restSecondsMin: 150, restSecondsMax: 210, substitutionGroup: 'squat_pattern' }),
        ex({ id: 'strength_base_a_bench_press', exerciseName: 'Bench Press', slotId: 'primary_press_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 4, repsMin: 4, repsMax: 6, restSecondsMin: 150, restSecondsMax: 210, substitutionGroup: 'horizontal_press' }),
        ex({ id: 'strength_base_a_chest_supported_row', exerciseName: 'Chest-Supported Row', slotId: 'secondary_pull_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 3, repsMin: 6, repsMax: 8, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'horizontal_pull' }),
        ex({ id: 'strength_base_a_cable_crunch', exerciseName: 'Cable Crunch', slotId: 'accessory_core_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_core' }),
      ] }),
      session({ id: 'strength_base_b', name: 'Strength B', orderIndex: 2, exercises: [
        ex({ id: 'strength_base_b_trap_bar_deadlift', exerciseName: 'Trap Bar Deadlift', slotId: 'primary_hinge_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 4, repsMin: 3, repsMax: 5, restSecondsMin: 150, restSecondsMax: 210, substitutionGroup: 'hinge_pattern' }),
        ex({ id: 'strength_base_b_overhead_press', exerciseName: 'Overhead Press', slotId: 'primary_press_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 4, repsMin: 4, repsMax: 6, restSecondsMin: 150, restSecondsMax: 210, substitutionGroup: 'vertical_press' }),
        ex({ id: 'strength_base_b_lat_pulldown', exerciseName: 'Lat Pulldown', slotId: 'secondary_pull_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 3, repsMin: 6, repsMax: 8, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'vertical_pull' }),
        ex({ id: 'strength_base_b_reverse_lunge', exerciseName: 'Reverse Lunge', slotId: 'secondary_single_leg_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 2, repsMin: 8, repsMax: 10, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'single_leg' }),
      ] }),
      session({ id: 'strength_base_c', name: 'Strength C', orderIndex: 3, exercises: [
        ex({ id: 'strength_base_c_front_squat', exerciseName: 'Front Squat', slotId: 'primary_squat_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 4, repsMax: 6, restSecondsMin: 150, restSecondsMax: 210, substitutionGroup: 'squat_pattern' }),
        ex({ id: 'strength_base_c_incline_bench_press', exerciseName: 'Incline Bench Press', slotId: 'primary_press_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 5, repsMax: 7, restSecondsMin: 150, restSecondsMax: 210, substitutionGroup: 'horizontal_press' }),
        ex({ id: 'strength_base_c_barbell_row', exerciseName: 'Barbell Row', slotId: 'secondary_pull_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 3, repsMin: 6, repsMax: 8, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'horizontal_pull' }),
        ex({ id: 'strength_base_c_hanging_knee_raise', exerciseName: 'Hanging Knee Raise', slotId: 'accessory_core_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'bodyweight', sets: 2, repsMin: 10, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_core' }),
      ] }),
    ],
  },
  {
    id: 'tpl_4_day_powerbuilding_v1',
    name: '4-Day Powerbuilding',
    goalType: 'strength',
    level: 'intermediate',
    splitType: 'upper_lower',
    daysPerWeek: 4,
    estimatedSessionDuration: 60,
    progressionModel: 'double_progression',
    defaultScheduleMode: 'rolling_sequence',
    progressionRules: {
      primary: 'Run the first lift of each day as the performance anchor. Add load after every set lands at the top of the target range with clean technique.',
      secondary: 'Use secondary compounds to add quality volume without matching the fatigue of the main lift.',
      accessory: 'Accessories should support muscle gain and joint balance. Add reps first and keep them from disrupting recovery for the next heavy day.',
      failureHandling: 'Missed reps on the first hard set means hold the same load next time. Two misses in a row means reduce load slightly and rebuild the week cleanly.',
    },
    sessions: [
      session({ id: 'power_upper_strength', name: 'Upper Strength', orderIndex: 1, exercises: [
        ex({ id: 'power_upper_strength_bench_press', exerciseName: 'Bench Press', slotId: 'primary_press_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 4, repsMin: 3, repsMax: 5, restSecondsMin: 150, restSecondsMax: 210, substitutionGroup: 'horizontal_press' }),
        ex({ id: 'power_upper_strength_barbell_row', exerciseName: 'Barbell Row', slotId: 'primary_pull_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 4, repsMin: 4, repsMax: 6, restSecondsMin: 150, restSecondsMax: 210, substitutionGroup: 'horizontal_pull' }),
        ex({ id: 'power_upper_strength_overhead_press', exerciseName: 'Overhead Press', slotId: 'secondary_press_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 3, repsMin: 5, repsMax: 7, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'vertical_press' }),
        ex({ id: 'power_upper_strength_lat_pulldown', exerciseName: 'Lat Pulldown', slotId: 'secondary_pull_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 3, repsMin: 6, repsMax: 8, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'vertical_pull' }),
        ex({ id: 'power_upper_strength_triceps_pushdown', exerciseName: 'Triceps Pushdown', slotId: 'accessory_arms_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_arms' }),
      ] }),
      session({ id: 'power_lower_strength', name: 'Lower Strength', orderIndex: 2, exercises: [
        ex({ id: 'power_lower_strength_back_squat', exerciseName: 'Back Squat', slotId: 'primary_squat_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 4, repsMin: 3, repsMax: 5, restSecondsMin: 150, restSecondsMax: 210, substitutionGroup: 'squat_pattern' }),
        ex({ id: 'power_lower_strength_trap_bar_deadlift', exerciseName: 'Trap Bar Deadlift', slotId: 'primary_hinge_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 3, repsMax: 5, restSecondsMin: 150, restSecondsMax: 210, substitutionGroup: 'hinge_pattern' }),
        ex({ id: 'power_lower_strength_leg_press', exerciseName: 'Leg Press', slotId: 'secondary_squat_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 3, repsMin: 6, repsMax: 8, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'squat_pattern' }),
        ex({ id: 'power_lower_strength_leg_curl', exerciseName: 'Leg Curl', slotId: 'accessory_hamstrings_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_hamstrings' }),
        ex({ id: 'power_lower_strength_cable_crunch', exerciseName: 'Cable Crunch', slotId: 'accessory_core_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_core' }),
      ] }),
      session({ id: 'power_upper_volume', name: 'Upper Volume', orderIndex: 3, exercises: [
        ex({ id: 'power_upper_volume_incline_dumbbell_press', exerciseName: 'Incline Dumbbell Press', slotId: 'primary_press_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 8, repsMax: 10, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'horizontal_press' }),
        ex({ id: 'power_upper_volume_chest_supported_row', exerciseName: 'Chest-Supported Row', slotId: 'primary_pull_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 8, repsMax: 10, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'horizontal_pull' }),
        ex({ id: 'power_upper_volume_machine_chest_press', exerciseName: 'Machine Chest Press', slotId: 'secondary_press_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'horizontal_press' }),
        ex({ id: 'power_upper_volume_rear_delt_fly', exerciseName: 'Rear Delt Fly', slotId: 'accessory_delts_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 12, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_delts' }),
        ex({ id: 'power_upper_volume_dumbbell_curl', exerciseName: 'Dumbbell Curl', slotId: 'accessory_arms_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_arms' }),
      ] }),
      session({ id: 'power_lower_volume', name: 'Lower Volume', orderIndex: 4, exercises: [
        ex({ id: 'power_lower_volume_front_squat', exerciseName: 'Front Squat', slotId: 'primary_squat_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 6, repsMax: 8, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'squat_pattern' }),
        ex({ id: 'power_lower_volume_romanian_deadlift', exerciseName: 'Romanian Deadlift', slotId: 'primary_hinge_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 6, repsMax: 8, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'hinge_pattern' }),
        ex({ id: 'power_lower_volume_bulgarian_split_squat', exerciseName: 'Bulgarian Split Squat', slotId: 'secondary_single_leg_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 2, repsMin: 8, repsMax: 10, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'single_leg' }),
        ex({ id: 'power_lower_volume_calf_raise', exerciseName: 'Calf Raise', slotId: 'calves_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 12, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'calves' }),
        ex({ id: 'power_lower_volume_hanging_knee_raise', exerciseName: 'Hanging Knee Raise', slotId: 'accessory_core_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'bodyweight', sets: 2, repsMin: 10, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_core' }),
      ] }),
    ],
  },
  {
    id: 'tpl_2_day_beginner_strength_v1',
    name: '2-Day Beginner Strength',
    goalType: 'strength',
    level: 'beginner',
    splitType: 'full_body',
    daysPerWeek: 2,
    estimatedSessionDuration: 50,
    progressionModel: 'double_progression',
    defaultScheduleMode: 'rolling_sequence',
    progressionRules: {
      primary: 'Drive the main lift with lower-rep double progression. Add load only when all planned sets stay clean and inside the target range.',
      secondary: 'Keep secondary lifts one step easier than the main lift so the week stays repeatable.',
      accessory: 'Use accessories to support the main patterns, but keep the total workload low enough that recovery stays obvious.',
      failureHandling: 'If the first hard set misses repsMin, repeat the same load next time. Two misses in a row means reduce load slightly and rebuild.',
    },
    sessions: [
      session({ id: 'beginner_strength_a', name: 'Strength A', orderIndex: 1, exercises: [
        ex({ id: 'beginner_strength_a_back_squat', exerciseName: 'Back Squat', slotId: 'primary_squat_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 4, repsMin: 4, repsMax: 6, restSecondsMin: 150, restSecondsMax: 210, substitutionGroup: 'squat_pattern' }),
        ex({ id: 'beginner_strength_a_bench_press', exerciseName: 'Bench Press', slotId: 'primary_press_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 4, repsMin: 4, repsMax: 6, restSecondsMin: 150, restSecondsMax: 210, substitutionGroup: 'horizontal_press' }),
        ex({ id: 'beginner_strength_a_chest_supported_row', exerciseName: 'Chest-Supported Row', slotId: 'secondary_pull_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 3, repsMin: 6, repsMax: 8, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'horizontal_pull' }),
        ex({ id: 'beginner_strength_a_cable_crunch', exerciseName: 'Cable Crunch', slotId: 'accessory_core_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_core' }),
      ] }),
      session({ id: 'beginner_strength_b', name: 'Strength B', orderIndex: 2, exercises: [
        ex({ id: 'beginner_strength_b_trap_bar_deadlift', exerciseName: 'Trap Bar Deadlift', slotId: 'primary_hinge_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 4, repsMin: 3, repsMax: 5, restSecondsMin: 150, restSecondsMax: 210, substitutionGroup: 'hinge_pattern' }),
        ex({ id: 'beginner_strength_b_overhead_press', exerciseName: 'Overhead Press', slotId: 'primary_press_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 4, repsMin: 4, repsMax: 6, restSecondsMin: 150, restSecondsMax: 210, substitutionGroup: 'vertical_press' }),
        ex({ id: 'beginner_strength_b_lat_pulldown', exerciseName: 'Lat Pulldown', slotId: 'secondary_pull_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 3, repsMin: 6, repsMax: 8, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'vertical_pull' }),
        ex({ id: 'beginner_strength_b_reverse_lunge', exerciseName: 'Reverse Lunge', slotId: 'secondary_single_leg_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 2, repsMin: 8, repsMax: 10, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'single_leg' }),
      ] }),
    ],
  },

  {
    id: 'tpl_3_day_upper_lower_lite_v1',
    name: '3-Day Upper/Lower Lite',
    goalType: 'general',
    level: 'beginner',
    splitType: 'upper_lower',
    daysPerWeek: 3,
    estimatedSessionDuration: 50,
    progressionModel: 'double_progression',
    defaultScheduleMode: 'rolling_sequence',
    progressionRules: {
      primary: 'Use double progression on the first two lifts each day and add load after the top of the rep range repeats with good form.',
      secondary: 'Let the secondary compounds climb more slowly so session quality stays consistent across the week.',
      accessory: 'Treat accessory lifts as easy volume that rounds the session out without making recovery harder than it needs to be.',
      failureHandling: 'If a main lift misses repsMin, hold the same load next time. Two misses in a row means reduce load slightly and rebuild.',
    },
    sessions: [
      session({ id: 'upper_lower_lite_upper_a', name: 'Upper A', orderIndex: 1, exercises: [
        ex({ id: 'upper_lower_lite_upper_a_incline_dumbbell_press', exerciseName: 'Incline Dumbbell Press', slotId: 'primary_press_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 8, repsMax: 10, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'horizontal_press' }),
        ex({ id: 'upper_lower_lite_upper_a_chest_supported_row', exerciseName: 'Chest-Supported Row', slotId: 'primary_pull_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 8, repsMax: 10, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'horizontal_pull' }),
        ex({ id: 'upper_lower_lite_upper_a_overhead_press', exerciseName: 'Overhead Press', slotId: 'secondary_press_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 2, repsMin: 6, repsMax: 8, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'vertical_press' }),
        ex({ id: 'upper_lower_lite_upper_a_lat_pulldown', exerciseName: 'Lat Pulldown', slotId: 'secondary_pull_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 2, repsMin: 8, repsMax: 10, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'vertical_pull' }),
        ex({ id: 'upper_lower_lite_upper_a_lateral_raise', exerciseName: 'Lateral Raise', slotId: 'accessory_delts_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 12, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_delts' }),
      ] }),
      session({ id: 'upper_lower_lite_lower', name: 'Lower', orderIndex: 2, exercises: [
        ex({ id: 'upper_lower_lite_lower_leg_press', exerciseName: 'Leg Press', slotId: 'primary_squat_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 8, repsMax: 10, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'squat_pattern' }),
        ex({ id: 'upper_lower_lite_lower_romanian_deadlift', exerciseName: 'Romanian Deadlift', slotId: 'primary_hinge_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 8, repsMax: 10, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'hinge_pattern' }),
        ex({ id: 'upper_lower_lite_lower_reverse_lunge', exerciseName: 'Reverse Lunge', slotId: 'secondary_single_leg_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 2, repsMin: 8, repsMax: 10, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'single_leg' }),
        ex({ id: 'upper_lower_lite_lower_leg_curl', exerciseName: 'Leg Curl', slotId: 'accessory_hamstrings_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_hamstrings' }),
        ex({ id: 'upper_lower_lite_lower_calf_raise', exerciseName: 'Calf Raise', slotId: 'calves_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 12, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'calves' }),
        ex({ id: 'upper_lower_lite_lower_cable_crunch', exerciseName: 'Cable Crunch', slotId: 'accessory_core_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_core' }),
      ] }),
      session({ id: 'upper_lower_lite_upper_b', name: 'Upper B', orderIndex: 3, exercises: [
        ex({ id: 'upper_lower_lite_upper_b_machine_chest_press', exerciseName: 'Machine Chest Press', slotId: 'primary_press_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 8, repsMax: 10, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'horizontal_press' }),
        ex({ id: 'upper_lower_lite_upper_b_seated_cable_row', exerciseName: 'Seated Cable Row', slotId: 'primary_pull_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 8, repsMax: 10, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'horizontal_pull' }),
        ex({ id: 'upper_lower_lite_upper_b_dumbbell_shoulder_press', exerciseName: 'Dumbbell Shoulder Press', slotId: 'secondary_press_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 2, repsMin: 8, repsMax: 10, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'vertical_press' }),
        ex({ id: 'upper_lower_lite_upper_b_rear_delt_fly', exerciseName: 'Rear Delt Fly', slotId: 'accessory_delts_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 12, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_delts' }),
        ex({ id: 'upper_lower_lite_upper_b_triceps_pushdown', exerciseName: 'Triceps Pushdown', slotId: 'accessory_arms_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_arms' }),
        ex({ id: 'upper_lower_lite_upper_b_dumbbell_curl', exerciseName: 'Dumbbell Curl', slotId: 'accessory_arms_2', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_arms' }),
      ] }),
    ],
  },

  {
    id: 'tpl_3_day_push_pull_legs_v1',
    name: '3-Day Push Pull Legs',
    goalType: 'hypertrophy',
    level: 'intermediate',
    splitType: 'hybrid',
    daysPerWeek: 3,
    estimatedSessionDuration: 55,
    progressionModel: 'double_progression',
    defaultScheduleMode: 'rolling_sequence',
    progressionRules: {
      primary: 'Push the first compound lift on each day through the rep range before adding load.',
      secondary: 'Secondary compounds add volume, so let them rise more slowly than the anchor of the day.',
      accessory: 'Accessories should chase clean reps and a pump without creating sloppy fatigue for the next session.',
      failureHandling: 'If the first hard set misses repsMin, repeat the same load. If it misses twice, reduce load slightly and rebuild.',
    },
    sessions: [
      session({ id: 'push_pull_legs_push', name: 'Push', orderIndex: 1, exercises: [
        ex({ id: 'push_pull_legs_push_bench_press', exerciseName: 'Bench Press', slotId: 'primary_press_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 6, repsMax: 8, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'horizontal_press' }),
        ex({ id: 'push_pull_legs_push_incline_dumbbell_press', exerciseName: 'Incline Dumbbell Press', slotId: 'secondary_press_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 3, repsMin: 8, repsMax: 10, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'horizontal_press' }),
        ex({ id: 'push_pull_legs_push_machine_chest_press', exerciseName: 'Machine Chest Press', slotId: 'secondary_press_2', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'horizontal_press' }),
        ex({ id: 'push_pull_legs_push_lateral_raise', exerciseName: 'Lateral Raise', slotId: 'accessory_delts_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 12, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_delts' }),
        ex({ id: 'push_pull_legs_push_triceps_pushdown', exerciseName: 'Triceps Pushdown', slotId: 'accessory_arms_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_arms' }),
      ] }),
      session({ id: 'push_pull_legs_pull', name: 'Pull', orderIndex: 2, exercises: [
        ex({ id: 'push_pull_legs_pull_lat_pulldown', exerciseName: 'Lat Pulldown', slotId: 'primary_pull_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 8, repsMax: 10, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'vertical_pull' }),
        ex({ id: 'push_pull_legs_pull_chest_supported_row', exerciseName: 'Chest-Supported Row', slotId: 'primary_pull_2', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 8, repsMax: 10, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'horizontal_pull' }),
        ex({ id: 'push_pull_legs_pull_seated_cable_row', exerciseName: 'Seated Cable Row', slotId: 'secondary_pull_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'horizontal_pull' }),
        ex({ id: 'push_pull_legs_pull_rear_delt_fly', exerciseName: 'Rear Delt Fly', slotId: 'accessory_delts_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 12, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_delts' }),
        ex({ id: 'push_pull_legs_pull_dumbbell_curl', exerciseName: 'Dumbbell Curl', slotId: 'accessory_arms_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_arms' }),
        ex({ id: 'push_pull_legs_pull_hammer_curl', exerciseName: 'Hammer Curl', slotId: 'accessory_arms_2', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_arms' }),
      ] }),
      session({ id: 'push_pull_legs_legs', name: 'Legs', orderIndex: 3, exercises: [
        ex({ id: 'push_pull_legs_legs_back_squat', exerciseName: 'Back Squat', slotId: 'primary_squat_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 6, repsMax: 8, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'squat_pattern' }),
        ex({ id: 'push_pull_legs_legs_romanian_deadlift', exerciseName: 'Romanian Deadlift', slotId: 'primary_hinge_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 8, repsMax: 10, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'hinge_pattern' }),
        ex({ id: 'push_pull_legs_legs_leg_press', exerciseName: 'Leg Press', slotId: 'secondary_squat_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'squat_pattern' }),
        ex({ id: 'push_pull_legs_legs_leg_curl', exerciseName: 'Leg Curl', slotId: 'accessory_hamstrings_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_hamstrings' }),
        ex({ id: 'push_pull_legs_legs_calf_raise', exerciseName: 'Calf Raise', slotId: 'calves_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 12, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'calves' }),
        ex({ id: 'push_pull_legs_legs_hanging_knee_raise', exerciseName: 'Hanging Knee Raise', slotId: 'accessory_core_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'bodyweight', sets: 2, repsMin: 10, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_core' }),
      ] }),
    ],
  },

  {
    id: 'tpl_4_day_muscle_builder_v1',
    name: '4-Day Muscle Builder',
    goalType: 'hypertrophy',
    level: 'beginner',
    splitType: 'upper_lower',
    daysPerWeek: 4,
    estimatedSessionDuration: 55,
    progressionModel: 'double_progression',
    defaultScheduleMode: 'rolling_sequence',
    progressionRules: {
      primary: 'Progress the first compound lift of each session through the rep range before adding load.',
      secondary: 'Secondary lifts add most of the weekly volume, so keep them technical and avoid forcing progress too aggressively.',
      accessory: 'Accessories should be smooth, high-quality sets that fill out the session without wrecking the next one.',
      failureHandling: 'If a main lift misses repsMin, repeat it next time. Two misses in a row means reduce load slightly and rebuild the pattern.',
    },
    sessions: [
      session({ id: 'muscle_builder_upper_a', name: 'Upper A', orderIndex: 1, exercises: [
        ex({ id: 'muscle_builder_upper_a_machine_chest_press', exerciseName: 'Machine Chest Press', slotId: 'primary_press_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 8, repsMax: 10, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'horizontal_press' }),
        ex({ id: 'muscle_builder_upper_a_lat_pulldown', exerciseName: 'Lat Pulldown', slotId: 'primary_pull_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 8, repsMax: 10, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'vertical_pull' }),
        ex({ id: 'muscle_builder_upper_a_incline_dumbbell_press', exerciseName: 'Incline Dumbbell Press', slotId: 'secondary_press_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'horizontal_press' }),
        ex({ id: 'muscle_builder_upper_a_seated_cable_row', exerciseName: 'Seated Cable Row', slotId: 'secondary_pull_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'horizontal_pull' }),
        ex({ id: 'muscle_builder_upper_a_lateral_raise', exerciseName: 'Lateral Raise', slotId: 'accessory_delts_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 12, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_delts' }),
        ex({ id: 'muscle_builder_upper_a_triceps_pushdown', exerciseName: 'Triceps Pushdown', slotId: 'accessory_arms_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_arms' }),
      ] }),
      session({ id: 'muscle_builder_lower_a', name: 'Lower A', orderIndex: 2, exercises: [
        ex({ id: 'muscle_builder_lower_a_back_squat', exerciseName: 'Back Squat', slotId: 'primary_squat_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 6, repsMax: 8, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'squat_pattern' }),
        ex({ id: 'muscle_builder_lower_a_romanian_deadlift', exerciseName: 'Romanian Deadlift', slotId: 'primary_hinge_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 8, repsMax: 10, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'hinge_pattern' }),
        ex({ id: 'muscle_builder_lower_a_leg_press', exerciseName: 'Leg Press', slotId: 'secondary_squat_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'squat_pattern' }),
        ex({ id: 'muscle_builder_lower_a_leg_curl', exerciseName: 'Leg Curl', slotId: 'accessory_hamstrings_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_hamstrings' }),
        ex({ id: 'muscle_builder_lower_a_calf_raise', exerciseName: 'Calf Raise', slotId: 'calves_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 12, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'calves' }),
        ex({ id: 'muscle_builder_lower_a_cable_crunch', exerciseName: 'Cable Crunch', slotId: 'accessory_core_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_core' }),
      ] }),
      session({ id: 'muscle_builder_upper_b', name: 'Upper B', orderIndex: 3, exercises: [
        ex({ id: 'muscle_builder_upper_b_bench_press', exerciseName: 'Bench Press', slotId: 'primary_press_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 6, repsMax: 8, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'horizontal_press' }),
        ex({ id: 'muscle_builder_upper_b_chest_supported_row', exerciseName: 'Chest-Supported Row', slotId: 'primary_pull_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 8, repsMax: 10, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'horizontal_pull' }),
        ex({ id: 'muscle_builder_upper_b_dumbbell_shoulder_press', exerciseName: 'Dumbbell Shoulder Press', slotId: 'secondary_press_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 2, repsMin: 8, repsMax: 10, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'vertical_press' }),
        ex({ id: 'muscle_builder_upper_b_rear_delt_fly', exerciseName: 'Rear Delt Fly', slotId: 'accessory_delts_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 12, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_delts' }),
        ex({ id: 'muscle_builder_upper_b_dumbbell_curl', exerciseName: 'Dumbbell Curl', slotId: 'accessory_arms_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_arms' }),
        ex({ id: 'muscle_builder_upper_b_hammer_curl', exerciseName: 'Hammer Curl', slotId: 'accessory_arms_2', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_arms' }),
      ] }),
      session({ id: 'muscle_builder_lower_b', name: 'Lower B', orderIndex: 4, exercises: [
        ex({ id: 'muscle_builder_lower_b_hack_squat', exerciseName: 'Hack Squat', slotId: 'primary_squat_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 8, repsMax: 10, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'squat_pattern' }),
        ex({ id: 'muscle_builder_lower_b_hip_thrust', exerciseName: 'Hip Thrust', slotId: 'primary_hinge_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 8, repsMax: 10, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'hinge_pattern' }),
        ex({ id: 'muscle_builder_lower_b_bulgarian_split_squat', exerciseName: 'Bulgarian Split Squat', slotId: 'secondary_single_leg_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 2, repsMin: 8, repsMax: 10, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'single_leg' }),
        ex({ id: 'muscle_builder_lower_b_leg_curl', exerciseName: 'Leg Curl', slotId: 'accessory_hamstrings_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_hamstrings' }),
        ex({ id: 'muscle_builder_lower_b_calf_raise', exerciseName: 'Calf Raise', slotId: 'calves_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 12, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'calves' }),
        ex({ id: 'muscle_builder_lower_b_hanging_knee_raise', exerciseName: 'Hanging Knee Raise', slotId: 'accessory_core_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'bodyweight', sets: 2, repsMin: 10, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_core' }),
      ] }),
    ],
  },

  {
    id: 'tpl_4_day_strength_size_v1',
    name: '4-Day Strength + Size',
    goalType: 'strength',
    level: 'intermediate',
    splitType: 'upper_lower',
    daysPerWeek: 4,
    estimatedSessionDuration: 60,
    progressionModel: 'double_progression',
    defaultScheduleMode: 'rolling_sequence',
    progressionRules: {
      primary: 'Treat the first lift on each day as the performance slot and only add load once all work sets live at the top of the target range.',
      secondary: 'Use the second compound lift to build more total work without matching the fatigue of the anchor.',
      accessory: 'Accessories should improve recovery and muscle balance, not compete with the heavy work.',
      failureHandling: 'Miss repsMin on the anchor lift and you repeat the load. Miss it twice and back off slightly before rebuilding.',
    },
    sessions: [
      session({ id: 'strength_size_upper_performance', name: 'Upper Performance', orderIndex: 1, exercises: [
        ex({ id: 'strength_size_upper_performance_bench_press', exerciseName: 'Bench Press', slotId: 'primary_press_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 4, repsMin: 3, repsMax: 5, restSecondsMin: 150, restSecondsMax: 210, substitutionGroup: 'horizontal_press' }),
        ex({ id: 'strength_size_upper_performance_barbell_row', exerciseName: 'Barbell Row', slotId: 'primary_pull_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 4, repsMin: 4, repsMax: 6, restSecondsMin: 150, restSecondsMax: 210, substitutionGroup: 'horizontal_pull' }),
        ex({ id: 'strength_size_upper_performance_overhead_press', exerciseName: 'Overhead Press', slotId: 'secondary_press_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 3, repsMin: 5, repsMax: 7, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'vertical_press' }),
        ex({ id: 'strength_size_upper_performance_lat_pulldown', exerciseName: 'Lat Pulldown', slotId: 'secondary_pull_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 3, repsMin: 6, repsMax: 8, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'vertical_pull' }),
        ex({ id: 'strength_size_upper_performance_triceps_pushdown', exerciseName: 'Triceps Pushdown', slotId: 'accessory_arms_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_arms' }),
      ] }),
      session({ id: 'strength_size_lower_performance', name: 'Lower Performance', orderIndex: 2, exercises: [
        ex({ id: 'strength_size_lower_performance_back_squat', exerciseName: 'Back Squat', slotId: 'primary_squat_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 4, repsMin: 3, repsMax: 5, restSecondsMin: 150, restSecondsMax: 210, substitutionGroup: 'squat_pattern' }),
        ex({ id: 'strength_size_lower_performance_trap_bar_deadlift', exerciseName: 'Trap Bar Deadlift', slotId: 'primary_hinge_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 3, repsMax: 5, restSecondsMin: 150, restSecondsMax: 210, substitutionGroup: 'hinge_pattern' }),
        ex({ id: 'strength_size_lower_performance_leg_press', exerciseName: 'Leg Press', slotId: 'secondary_squat_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 3, repsMin: 6, repsMax: 8, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'squat_pattern' }),
        ex({ id: 'strength_size_lower_performance_cable_crunch', exerciseName: 'Cable Crunch', slotId: 'accessory_core_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_core' }),
      ] }),
      session({ id: 'strength_size_upper_growth', name: 'Upper Growth', orderIndex: 3, exercises: [
        ex({ id: 'strength_size_upper_growth_incline_bench_press', exerciseName: 'Incline Bench Press', slotId: 'primary_press_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 6, repsMax: 8, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'horizontal_press' }),
        ex({ id: 'strength_size_upper_growth_chest_supported_row', exerciseName: 'Chest-Supported Row', slotId: 'primary_pull_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 6, repsMax: 8, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'horizontal_pull' }),
        ex({ id: 'strength_size_upper_growth_machine_chest_press', exerciseName: 'Machine Chest Press', slotId: 'secondary_press_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 2, repsMin: 8, repsMax: 10, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'horizontal_press' }),
        ex({ id: 'strength_size_upper_growth_lateral_raise', exerciseName: 'Lateral Raise', slotId: 'accessory_delts_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 12, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_delts' }),
        ex({ id: 'strength_size_upper_growth_dumbbell_curl', exerciseName: 'Dumbbell Curl', slotId: 'accessory_arms_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_arms' }),
      ] }),
      session({ id: 'strength_size_lower_growth', name: 'Lower Growth', orderIndex: 4, exercises: [
        ex({ id: 'strength_size_lower_growth_front_squat', exerciseName: 'Front Squat', slotId: 'primary_squat_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 6, repsMax: 8, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'squat_pattern' }),
        ex({ id: 'strength_size_lower_growth_romanian_deadlift', exerciseName: 'Romanian Deadlift', slotId: 'primary_hinge_1', role: 'primary', progressionPriority: 'high', trackingMode: 'load_and_reps', sets: 3, repsMin: 6, repsMax: 8, restSecondsMin: 120, restSecondsMax: 150, substitutionGroup: 'hinge_pattern' }),
        ex({ id: 'strength_size_lower_growth_reverse_lunge', exerciseName: 'Reverse Lunge', slotId: 'secondary_single_leg_1', role: 'secondary', progressionPriority: 'medium', trackingMode: 'load_and_reps', sets: 2, repsMin: 8, repsMax: 10, restSecondsMin: 90, restSecondsMax: 120, substitutionGroup: 'single_leg' }),
        ex({ id: 'strength_size_lower_growth_leg_curl', exerciseName: 'Leg Curl', slotId: 'accessory_hamstrings_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 10, repsMax: 12, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'accessory_hamstrings' }),
        ex({ id: 'strength_size_lower_growth_calf_raise', exerciseName: 'Calf Raise', slotId: 'calves_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 12, repsMax: 15, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'calves' }),
      ] }),
    ],
  },

  {
    id: 'tpl_2_day_mobility_reset_v1',
    name: '2-Day Mobility Reset',
    goalType: 'general',
    level: 'beginner',
    splitType: 'hybrid',
    daysPerWeek: 2,
    estimatedSessionDuration: 30,
    progressionModel: 'double_progression',
    defaultScheduleMode: 'rolling_sequence',
    progressionRules: {
      primary: 'Keep the movement smooth and repeat the full range before adding more total rounds.',
      secondary: 'Treat secondary drills as clean support work, not something to grind through.',
      accessory: 'Accessories should restore position and help you leave the session feeling better than when you started.',
      failureHandling: 'If a drill feels rough, repeat the same dose next time instead of adding more rounds or rushing range.',
    },
    sessions: [
      session({ id: 'mobility_reset_a', name: 'Mobility Reset A', orderIndex: 1, exercises: [
        ex({ id: 'mobility_reset_a_mobility_flow', exerciseName: 'Mobility Flow', slotId: 'mobility_1', role: 'primary', progressionPriority: 'medium', trackingMode: 'bodyweight', sets: 3, repsMin: 4, repsMax: 6, restSecondsMin: 30, restSecondsMax: 45, substitutionGroup: 'mobility_flow' }),
        ex({ id: 'mobility_reset_a_hip_mobility_flow', exerciseName: 'Hip Mobility Flow', slotId: 'mobility_2', role: 'secondary', progressionPriority: 'low', trackingMode: 'bodyweight', sets: 3, repsMin: 4, repsMax: 6, restSecondsMin: 30, restSecondsMax: 45, substitutionGroup: 'mobility_flow' }),
        ex({ id: 'mobility_reset_a_recovery_stretch_flow', exerciseName: 'Recovery Stretch Flow', slotId: 'mobility_3', role: 'secondary', progressionPriority: 'low', trackingMode: 'bodyweight', sets: 2, repsMin: 4, repsMax: 6, restSecondsMin: 30, restSecondsMax: 45, substitutionGroup: 'mobility_flow' }),
        ex({ id: 'mobility_reset_a_breath_reset', exerciseName: 'Breath Reset', slotId: 'reset_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'bodyweight', sets: 2, repsMin: 3, repsMax: 5, restSecondsMin: 20, restSecondsMax: 30, substitutionGroup: 'yoga_flow' }),
      ] }),
      session({ id: 'mobility_reset_b', name: 'Mobility Reset B', orderIndex: 2, exercises: [
        ex({ id: 'mobility_reset_b_hip_mobility_flow', exerciseName: 'Hip Mobility Flow', slotId: 'mobility_1', role: 'primary', progressionPriority: 'medium', trackingMode: 'bodyweight', sets: 3, repsMin: 4, repsMax: 6, restSecondsMin: 30, restSecondsMax: 45, substitutionGroup: 'mobility_flow' }),
        ex({ id: 'mobility_reset_b_sun_salutation_flow', exerciseName: 'Sun Salutation Flow', slotId: 'mobility_2', role: 'secondary', progressionPriority: 'low', trackingMode: 'bodyweight', sets: 3, repsMin: 4, repsMax: 6, restSecondsMin: 30, restSecondsMax: 45, substitutionGroup: 'yoga_flow' }),
        ex({ id: 'mobility_reset_b_recovery_stretch_flow', exerciseName: 'Recovery Stretch Flow', slotId: 'mobility_3', role: 'secondary', progressionPriority: 'low', trackingMode: 'bodyweight', sets: 2, repsMin: 4, repsMax: 6, restSecondsMin: 30, restSecondsMax: 45, substitutionGroup: 'mobility_flow' }),
        ex({ id: 'mobility_reset_b_breath_reset', exerciseName: 'Breath Reset', slotId: 'reset_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'bodyweight', sets: 2, repsMin: 3, repsMax: 5, restSecondsMin: 20, restSecondsMax: 30, substitutionGroup: 'yoga_flow' }),
      ] }),
    ],
  },

  {
    id: 'tpl_2_day_yoga_recovery_v1',
    name: '2-Day Yoga Recovery',
    goalType: 'general',
    level: 'beginner',
    splitType: 'hybrid',
    daysPerWeek: 2,
    estimatedSessionDuration: 35,
    progressionModel: 'double_progression',
    defaultScheduleMode: 'rolling_sequence',
    progressionRules: {
      primary: 'Repeat the full flow smoothly before increasing total cycles.',
      secondary: 'Use secondary poses and resets to improve control, not to chase fatigue.',
      accessory: 'Accessories should improve breathing, range, and recovery quality from week to week.',
      failureHandling: 'If the flow quality drops, keep the same number of cycles next time and slow the pace down.',
    },
    sessions: [
      session({ id: 'yoga_recovery_a', name: 'Yoga Flow A', orderIndex: 1, exercises: [
        ex({ id: 'yoga_recovery_a_sun_salutation_flow', exerciseName: 'Sun Salutation Flow', slotId: 'flow_1', role: 'primary', progressionPriority: 'medium', trackingMode: 'bodyweight', sets: 3, repsMin: 4, repsMax: 6, restSecondsMin: 30, restSecondsMax: 45, substitutionGroup: 'yoga_flow' }),
        ex({ id: 'yoga_recovery_a_yoga_balance_flow', exerciseName: 'Yoga Balance Flow', slotId: 'flow_2', role: 'secondary', progressionPriority: 'low', trackingMode: 'bodyweight', sets: 3, repsMin: 3, repsMax: 5, restSecondsMin: 30, restSecondsMax: 45, substitutionGroup: 'yoga_flow' }),
        ex({ id: 'yoga_recovery_a_hip_mobility_flow', exerciseName: 'Hip Mobility Flow', slotId: 'flow_3', role: 'secondary', progressionPriority: 'low', trackingMode: 'bodyweight', sets: 2, repsMin: 4, repsMax: 6, restSecondsMin: 30, restSecondsMax: 45, substitutionGroup: 'mobility_flow' }),
        ex({ id: 'yoga_recovery_a_breath_reset', exerciseName: 'Breath Reset', slotId: 'reset_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'bodyweight', sets: 2, repsMin: 3, repsMax: 5, restSecondsMin: 20, restSecondsMax: 30, substitutionGroup: 'yoga_flow' }),
      ] }),
      session({ id: 'yoga_recovery_b', name: 'Yoga Flow B', orderIndex: 2, exercises: [
        ex({ id: 'yoga_recovery_b_yoga_balance_flow', exerciseName: 'Yoga Balance Flow', slotId: 'flow_1', role: 'primary', progressionPriority: 'medium', trackingMode: 'bodyweight', sets: 3, repsMin: 3, repsMax: 5, restSecondsMin: 30, restSecondsMax: 45, substitutionGroup: 'yoga_flow' }),
        ex({ id: 'yoga_recovery_b_recovery_stretch_flow', exerciseName: 'Recovery Stretch Flow', slotId: 'flow_2', role: 'secondary', progressionPriority: 'low', trackingMode: 'bodyweight', sets: 3, repsMin: 4, repsMax: 6, restSecondsMin: 30, restSecondsMax: 45, substitutionGroup: 'mobility_flow' }),
        ex({ id: 'yoga_recovery_b_mobility_flow', exerciseName: 'Mobility Flow', slotId: 'flow_3', role: 'secondary', progressionPriority: 'low', trackingMode: 'bodyweight', sets: 2, repsMin: 4, repsMax: 6, restSecondsMin: 30, restSecondsMax: 45, substitutionGroup: 'mobility_flow' }),
        ex({ id: 'yoga_recovery_b_breath_reset', exerciseName: 'Breath Reset', slotId: 'reset_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'bodyweight', sets: 2, repsMin: 3, repsMax: 5, restSecondsMin: 20, restSecondsMax: 30, substitutionGroup: 'yoga_flow' }),
      ] }),
    ],
  },

  {
    id: 'tpl_3_day_run_mobility_v1',
    name: '3-Day Run + Mobility',
    goalType: 'general',
    level: 'beginner',
    splitType: 'hybrid',
    daysPerWeek: 3,
    estimatedSessionDuration: 35,
    progressionModel: 'double_progression',
    defaultScheduleMode: 'rolling_sequence',
    progressionRules: {
      primary: 'Treat the run work as clean interval blocks and add total blocks only after pacing feels stable.',
      secondary: 'Use mobility drills to leave the session feeling looser, not more fatigued.',
      accessory: 'Accessories should help ankles, hips, and breathing recover between run days.',
      failureHandling: 'If the interval work feels too heavy, repeat the same number of blocks next time and keep the pace easier.',
    },
    sessions: [
      session({ id: 'run_mobility_easy', name: 'Easy Run Day', orderIndex: 1, exercises: [
        ex({ id: 'run_mobility_easy_run_blocks', exerciseName: 'Easy Run Blocks', slotId: 'run_1', role: 'primary', progressionPriority: 'medium', trackingMode: 'reps_first', sets: 4, repsMin: 3, repsMax: 5, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'running_blocks' }),
        ex({ id: 'run_mobility_easy_mobility_flow', exerciseName: 'Mobility Flow', slotId: 'reset_1', role: 'secondary', progressionPriority: 'low', trackingMode: 'bodyweight', sets: 2, repsMin: 4, repsMax: 6, restSecondsMin: 30, restSecondsMax: 45, substitutionGroup: 'mobility_flow' }),
        ex({ id: 'run_mobility_easy_calf_raise', exerciseName: 'Calf Raise', slotId: 'reset_2', role: 'accessory', progressionPriority: 'low', trackingMode: 'reps_first', sets: 2, repsMin: 12, repsMax: 15, restSecondsMin: 30, restSecondsMax: 45, substitutionGroup: 'calves' }),
      ] }),
      session({ id: 'run_mobility_tempo', name: 'Tempo Day', orderIndex: 2, exercises: [
        ex({ id: 'run_mobility_tempo_run_blocks', exerciseName: 'Tempo Run Blocks', slotId: 'run_1', role: 'primary', progressionPriority: 'medium', trackingMode: 'reps_first', sets: 5, repsMin: 2, repsMax: 4, restSecondsMin: 45, restSecondsMax: 75, substitutionGroup: 'running_blocks' }),
        ex({ id: 'run_mobility_tempo_stride_finishers', exerciseName: 'Stride Finishers', slotId: 'run_2', role: 'secondary', progressionPriority: 'low', trackingMode: 'reps_first', sets: 4, repsMin: 2, repsMax: 3, restSecondsMin: 30, restSecondsMax: 45, substitutionGroup: 'running_blocks' }),
        ex({ id: 'run_mobility_tempo_breath_reset', exerciseName: 'Breath Reset', slotId: 'reset_1', role: 'accessory', progressionPriority: 'low', trackingMode: 'bodyweight', sets: 2, repsMin: 3, repsMax: 5, restSecondsMin: 20, restSecondsMax: 30, substitutionGroup: 'yoga_flow' }),
      ] }),
      session({ id: 'run_mobility_reset', name: 'Reset Day', orderIndex: 3, exercises: [
        ex({ id: 'run_mobility_reset_recovery_stretch_flow', exerciseName: 'Recovery Stretch Flow', slotId: 'reset_1', role: 'primary', progressionPriority: 'low', trackingMode: 'bodyweight', sets: 3, repsMin: 4, repsMax: 6, restSecondsMin: 30, restSecondsMax: 45, substitutionGroup: 'mobility_flow' }),
        ex({ id: 'run_mobility_reset_hip_mobility_flow', exerciseName: 'Hip Mobility Flow', slotId: 'reset_2', role: 'secondary', progressionPriority: 'low', trackingMode: 'bodyweight', sets: 3, repsMin: 4, repsMax: 6, restSecondsMin: 30, restSecondsMax: 45, substitutionGroup: 'mobility_flow' }),
        ex({ id: 'run_mobility_reset_sun_salutation_flow', exerciseName: 'Sun Salutation Flow', slotId: 'reset_3', role: 'secondary', progressionPriority: 'low', trackingMode: 'bodyweight', sets: 2, repsMin: 4, repsMax: 5, restSecondsMin: 30, restSecondsMax: 45, substitutionGroup: 'yoga_flow' }),
        ex({ id: 'run_mobility_reset_breath_reset', exerciseName: 'Breath Reset', slotId: 'reset_4', role: 'accessory', progressionPriority: 'low', trackingMode: 'bodyweight', sets: 2, repsMin: 3, repsMax: 5, restSecondsMin: 20, restSecondsMax: 30, substitutionGroup: 'yoga_flow' }),
      ] }),
    ],
  },

];

export const CORE_WORKOUT_TEMPLATE_ID = 'tpl_4_day_upper_lower_v1';

export function getWorkoutTemplateById(templateId: string) {
  return WORKOUT_TEMPLATES_V1.find((template) => template.id === templateId) ?? null;
}

export function getWorkoutTemplateSessions(templateId: string) {
  const template = getWorkoutTemplateById(templateId);
  return template ? [...template.sessions].sort((left, right) => left.orderIndex - right.orderIndex) : [];
}
